// 520 daily prompts — ~74 weeks before the same question returns (day-of-year rotation).
export const DAILY_QUESTIONS_CATALOG = [
  { category: "Deep", question: "What's one small thing I do that makes you feel loved?" },
  { category: "Funny", question: "If we switched bodies for a day, what would you do first?" },
  { category: "Deep", question: "What's your favorite memory of us from this month?" },
  { category: "Romantic", question: "What song reminds you of our relationship?" },
  { category: "Fun", question: "If we could teleport anywhere right now, where would we go?" },
  { category: "Deep", question: "What's something new you'd love to try together?" },
  { category: "Funny", question: "What is the most \"us\" thing we do without trying?" },
  { category: "Romantic", question: "When did you first know you were falling for me?" },
  { category: "Fun", question: "What would our couple superpower be?" },
  { category: "Deep", question: "What do you need more of from me this week?" },
  { category: "Gratitude", question: "What did I do recently that you appreciated but never said thank you for?" },
  { category: "Future", question: "Where do you see us in five years — be specific." },
  { category: "Romantic", question: "What was your first impression of me, honestly?" },
  { category: "Funny", question: "What's the dumbest argument we've ever had?" },
  { category: "Deep", question: "When do you feel most emotionally connected to me?" },
  { category: "Fun", question: "If we had a free weekend with no plans, what would we do?" },
  { category: "Gratitude", question: "What quality of mine are you most grateful for right now?" },
  { category: "Future", question: "What's one tradition you want us to start as a couple?" },
  { category: "Romantic", question: "What's your favorite way I show affection?" },
  { category: "Deep", question: "What's something you've been holding back that you want to share?" },
  { category: "Funny", question: "What would our reality show be called?" },
  { category: "Fun", question: "What's a hobby we should pick up together?" },
  { category: "Deep", question: "How has being with me changed you?" },
  { category: "Romantic", question: "Describe our relationship in three words." },
  { category: "Future", question: "What's on your couple bucket list that we haven't done yet?" },
  { category: "Gratitude", question: "What's a hard moment we got through that made us stronger?" },
  { category: "Funny", question: "Who would play us in a movie about our relationship?" },
  { category: "Deep", question: "What makes you feel safe with me?" },
  { category: "Fun", question: "What's the best meal we've ever shared?" },
  { category: "Romantic", question: "What's a moment with me you replay in your head?" },
  { category: "Future", question: "How do you want us to celebrate our next anniversary?" },
  { category: "Deep", question: "What's one thing you wish I understood better about you?" },
  { category: "Gratitude", question: "When did you last feel proud to be my partner?" },
  { category: "Funny", question: "What's my most predictable habit — and do you secretly love it?" },
  { category: "Fun", question: "If we opened a business together, what would it be?" },
  { category: "Romantic", question: "What's the sweetest text I've ever sent you?" },
  { category: "Deep", question: "What does \"home\" mean to you — and am I part of it?" },
  { category: "Future", question: "What's one goal you want us to work toward this year?" },
  { category: "Gratitude", question: "What's something I do that always cheers you up?" },
  { category: "Funny", question: "What would our couple Halloween costume be?" },
  { category: "Deep", question: "What's your love language — and how can I speak it better?" },
  { category: "Romantic", question: "What's your favorite photo of us and why?" },
  { category: "Fun", question: "What game or activity should we do on our next date night?" },
  { category: "Future", question: "Where do you want to travel together next?" },
  { category: "Deep", question: "What's a fear you have about relationships that I can help ease?" },
  { category: "Gratitude", question: "What's the best advice I've ever given you?" },
  { category: "Funny", question: "What's my tell when I'm in a bad mood?" },
  { category: "Romantic", question: "What small gesture from me means the most?" },
  { category: "Deep", question: "When was the last time you felt truly seen by me?" },
  { category: "Fun", question: "What's a show we should binge-watch together?" },
  { category: "Future", question: "Do you want kids, pets, or neither — and how do we align?" },
  { category: "Gratitude", question: "What's one way I've helped you grow?" },
  { category: "Funny", question: "What's the weirdest food combo I've convinced you to try?" },
  { category: "Deep", question: "What's your ideal balance of together time vs. alone time?" },
  { category: "Romantic", question: "What's a date idea we've never done but should?" },
  { category: "Fun", question: "If we won a free vacation tomorrow, where are we going?" },
  { category: "Future", question: "What does your dream weekend with me look like?" },
  { category: "Deep", question: "What's something you admire about how I handle stress?" },
  { category: "Gratitude", question: "What's a sacrifice I've made for us that you noticed?" },
  { category: "Funny", question: "What nickname for me do you use when I'm not around?" },
  { category: "Romantic", question: "What's your favorite \"ordinary\" moment with me?" },
  { category: "Deep", question: "How do you prefer we resolve disagreements?" },
  { category: "Fun", question: "What's a playlist song that is 100% us?" },
  { category: "Future", question: "What kind of home do you imagine us living in someday?" },
  { category: "Gratitude", question: "What made you choose me?" },
  { category: "Funny", question: "What's the most embarrassing thing I've done in front of you?" },
  { category: "Deep", question: "What's one boundary that helps our relationship thrive?" },
  { category: "Romantic", question: "When do you feel most attracted to me — and why?" },
  { category: "Fun", question: "What's a challenge we should tackle as a team this month?" },
  { category: "Future", question: "What legacy do you want our relationship to leave?" },
  { category: "Deep", question: "What's one thing you want to forgive or let go of between us?" },
  { category: "Gratitude", question: "What's the best compliment I've ever given you?" },
  { category: "Funny", question: "If we were characters in a sitcom, who'd be the funny one?" },
  { category: "Romantic", question: "What's one thing I do that still gives you butterflies?" },
  { category: "Deep", question: "What does commitment mean to you in our relationship?" },
  { category: "Fun", question: "What's a silly tradition we should invent today?" },
  { category: "Future", question: "What's one skill you want us to learn together?" },
  { category: "Gratitude", question: "What's one thing about today you're glad we shared?" },
  { category: "Deep", question: "What emotion do you feel most often when you think about us that you have never told anyone?" },
  { category: "Deep", question: "What emotion do you feel most often when you think about us?" },
  { category: "Deep", question: "What part of our relationship do you want to nurture more that you want more of?" },
  { category: "Deep", question: "What part of our relationship do you want to nurture more?" },
  { category: "Deep", question: "When do you feel most like yourself around me right now?" },
  { category: "Deep", question: "When do you feel most like yourself around me?" },
  { category: "Deep", question: "What fear about love have I helped you release this season?" },
  { category: "Deep", question: "What fear about love have I helped you release?" },
  { category: "Deep", question: "What do you need from me on hard days before we met?" },
  { category: "Deep", question: "What do you need from me on hard days?" },
  { category: "Deep", question: "What belief about relationships has changed since we met on our worst day?" },
  { category: "Deep", question: "What belief about relationships has changed since we met?" },
  { category: "Deep", question: "What moment made you trust me more on our best day?" },
  { category: "Deep", question: "What moment made you trust me more?" },
  { category: "Deep", question: "What do you wish we talked about more openly when we are apart?" },
  { category: "Deep", question: "What do you wish we talked about more openly?" },
  { category: "Deep", question: "How do you know when you need space versus closeness when we are together?" },
  { category: "Deep", question: "How do you know when you need space versus closeness?" },
  { category: "Deep", question: "What does emotional intimacy look like for you that we have not tried yet?" },
  { category: "Deep", question: "What does emotional intimacy look like for you?" },
  { category: "Deep", question: "What pattern in our relationship would you like to improve that nobody else knows?" },
  { category: "Deep", question: "What pattern in our relationship would you like to improve?" },
  { category: "Deep", question: "When did you last feel vulnerable with me — and how did I respond that still surprises you?" },
  { category: "Deep", question: "When did you last feel vulnerable with me — and how did I respond?" },
  { category: "Deep", question: "What childhood lesson about love still affects you today that made you laugh?" },
  { category: "Deep", question: "What childhood lesson about love still affects you today?" },
  { category: "Deep", question: "What makes you feel chosen by me that made you tear up?" },
  { category: "Deep", question: "What makes you feel chosen by me?" },
  { category: "Deep", question: "What is one thing you are still learning about me from this year?" },
  { category: "Deep", question: "What is one thing you are still learning about me?" },
  { category: "Deep", question: "How has our love changed the way you see yourself from our first year?" },
  { category: "Deep", question: "How has our love changed the way you see yourself?" },
  { category: "Deep", question: "What do you need to hear from me more often that we should do more often?" },
  { category: "Deep", question: "What do you need to hear from me more often?" },
  { category: "Deep", question: "What conflict taught us something valuable that we should talk about tonight?" },
  { category: "Deep", question: "What conflict taught us something valuable?" },
  { category: "Deep", question: "What does forgiveness mean in our relationship that would strengthen us?" },
  { category: "Deep", question: "What does forgiveness mean in our relationship?" },
  { category: "Deep", question: "What boundary has made us stronger that feels uniquely us?" },
  { category: "Deep", question: "What boundary has made us stronger?" },
  { category: "Funny", question: "What is the most ridiculous thing we have argued about that you have never told anyone?" },
  { category: "Funny", question: "What is the most ridiculous thing we have argued about?" },
  { category: "Funny", question: "If we had a couple mascot, what would it be that you want more of?" },
  { category: "Funny", question: "If we had a couple mascot, what would it be?" },
  { category: "Funny", question: "What habit of mine would be a viral TikTok trend right now?" },
  { category: "Funny", question: "What habit of mine would be a viral TikTok trend?" },
  { category: "Funny", question: "What would our pet say about us if it could talk this season?" },
  { category: "Funny", question: "What would our pet say about us if it could talk?" },
  { category: "Funny", question: "What is my most dramatic reaction to something small before we met?" },
  { category: "Funny", question: "What is my most dramatic reaction to something small?" },
  { category: "Funny", question: "If we starred in a rom-com, what would the plot twist be on our worst day?" },
  { category: "Funny", question: "If we starred in a rom-com, what would the plot twist be?" },
  { category: "Funny", question: "What is the weirdest compliment I have given you on our best day?" },
  { category: "Funny", question: "What is the weirdest compliment I have given you?" },
  { category: "Funny", question: "What would our couple merch line sell when we are apart?" },
  { category: "Funny", question: "What would our couple merch line sell?" },
  { category: "Funny", question: "What inside joke should be on a T-shirt when we are together?" },
  { category: "Funny", question: "What inside joke should be on a T-shirt?" },
  { category: "Funny", question: "What is my go-to excuse when I am running late that we have not tried yet?" },
  { category: "Funny", question: "What is my go-to excuse when I am running late?" },
  { category: "Funny", question: "If we swapped phones for an hour, what would shock you that nobody else knows?" },
  { category: "Funny", question: "If we swapped phones for an hour, what would shock you?" },
  { category: "Funny", question: "What is the most chaotic date we have ever had that still surprises you?" },
  { category: "Funny", question: "What is the most chaotic date we have ever had?" },
  { category: "Funny", question: "What would our couple group chat name be that made you laugh?" },
  { category: "Funny", question: "What would our couple group chat name be?" },
  { category: "Funny", question: "What song would play when we enter a room that made you tear up?" },
  { category: "Funny", question: "What song would play when we enter a room?" },
  { category: "Funny", question: "What is my most predictable order at a restaurant from this year?" },
  { category: "Funny", question: "What is my most predictable order at a restaurant?" },
  { category: "Funny", question: "If we had a couple catchphrase, what is it from our first year?" },
  { category: "Funny", question: "If we had a couple catchphrase, what is it?" },
  { category: "Funny", question: "What would a documentary about us be titled that we should do more often?" },
  { category: "Funny", question: "What would a documentary about us be titled?" },
  { category: "Funny", question: "What is the funniest face I make without realizing that we should talk about tonight?" },
  { category: "Funny", question: "What is the funniest face I make without realizing?" },
  { category: "Funny", question: "What would our couple Halloween couple costume be this year that would strengthen us?" },
  { category: "Funny", question: "What would our couple Halloween couple costume be this year?" },
  { category: "Funny", question: "What is the most \"main character\" thing I have done that feels uniquely us?" },
  { category: "Funny", question: "What is the most \"main character\" thing I have done?" },
  { category: "Romantic", question: "What small moment with me still gives you butterflies that you have never told anyone?" },
  { category: "Romantic", question: "What small moment with me still gives you butterflies?" },
  { category: "Romantic", question: "What gesture from me feels most romantic that you want more of?" },
  { category: "Romantic", question: "What gesture from me feels most romantic?" },
  { category: "Romantic", question: "When did you first picture a future with me right now?" },
  { category: "Romantic", question: "When did you first picture a future with me?" },
  { category: "Romantic", question: "What scent or song instantly reminds you of us this season?" },
  { category: "Romantic", question: "What scent or song instantly reminds you of us?" },
  { category: "Romantic", question: "What is your favorite way we say goodbye before we met?" },
  { category: "Romantic", question: "What is your favorite way we say goodbye?" },
  { category: "Romantic", question: "What date with me do you want to recreate on our worst day?" },
  { category: "Romantic", question: "What date with me do you want to recreate?" },
  { category: "Romantic", question: "What do I do that makes you feel adored on our best day?" },
  { category: "Romantic", question: "What do I do that makes you feel adored?" },
  { category: "Romantic", question: "What is the most romantic thing I have ever said when we are apart?" },
  { category: "Romantic", question: "What is the most romantic thing I have ever said?" },
  { category: "Romantic", question: "What would your ideal slow morning with me look like when we are together?" },
  { category: "Romantic", question: "What would your ideal slow morning with me look like?" },
  { category: "Romantic", question: "What detail about me do you find irresistibly charming that we have not tried yet?" },
  { category: "Romantic", question: "What detail about me do you find irresistibly charming?" },
  { category: "Romantic", question: "What love note would you want to find from me that nobody else knows?" },
  { category: "Romantic", question: "What love note would you want to find from me?" },
  { category: "Romantic", question: "What moment made you think \"I am lucky\" that still surprises you?" },
  { category: "Romantic", question: "What moment made you think \"I am lucky\"?" },
  { category: "Romantic", question: "What is your favorite photo of us and why that made you laugh?" },
  { category: "Romantic", question: "What is your favorite photo of us and why?" },
  { category: "Romantic", question: "What would a perfect kiss-from-me moment be right now that made you tear up?" },
  { category: "Romantic", question: "What would a perfect kiss-from-me moment be right now?" },
  { category: "Romantic", question: "What tradition would make our relationship feel more romantic from this year?" },
  { category: "Romantic", question: "What tradition would make our relationship feel more romantic?" },
  { category: "Romantic", question: "What compliment from me do you replay in your head from our first year?" },
  { category: "Romantic", question: "What compliment from me do you replay in your head?" },
  { category: "Romantic", question: "What do you love about the way I look at you that we should do more often?" },
  { category: "Romantic", question: "What do you love about the way I look at you?" },
  { category: "Romantic", question: "What surprise from me would melt your heart today that we should talk about tonight?" },
  { category: "Romantic", question: "What surprise from me would melt your heart today?" },
  { category: "Romantic", question: "What is the sweetest thing we do without planning it that would strengthen us?" },
  { category: "Romantic", question: "What is the sweetest thing we do without planning it?" },
  { category: "Romantic", question: "What promise would you like us to make to each other that feels uniquely us?" },
  { category: "Romantic", question: "What promise would you like us to make to each other?" },
  { category: "Fun", question: "What adventure should we plan for next month that you have never told anyone?" },
  { category: "Fun", question: "What adventure should we plan for next month?" },
  { category: "Fun", question: "What game should we play on our next date night that you want more of?" },
  { category: "Fun", question: "What game should we play on our next date night?" },
  { category: "Fun", question: "What new food should we try together right now?" },
  { category: "Fun", question: "What new food should we try together?" },
  { category: "Fun", question: "What hobby could we pick up as a team this season?" },
  { category: "Fun", question: "What hobby could we pick up as a team?" },
  { category: "Fun", question: "What road trip playlist song is 100% us before we met?" },
  { category: "Fun", question: "What road trip playlist song is 100% us?" },
  { category: "Fun", question: "What would our dream game night include on our worst day?" },
  { category: "Fun", question: "What would our dream game night include?" },
  { category: "Fun", question: "What sport or activity should we learn together on our best day?" },
  { category: "Fun", question: "What sport or activity should we learn together?" },
  { category: "Fun", question: "What city should we explore on a weekend trip when we are apart?" },
  { category: "Fun", question: "What city should we explore on a weekend trip?" },
  { category: "Fun", question: "What challenge should we do as a couple this week when we are together?" },
  { category: "Fun", question: "What challenge should we do as a couple this week?" },
  { category: "Fun", question: "What show should we start watching tonight that we have not tried yet?" },
  { category: "Fun", question: "What show should we start watching tonight?" },
  { category: "Fun", question: "What silly competition should we have that nobody else knows?" },
  { category: "Fun", question: "What silly competition should we have?" },
  { category: "Fun", question: "What festival or event should we attend together that still surprises you?" },
  { category: "Fun", question: "What festival or event should we attend together?" },
  { category: "Fun", question: "What would our ideal lazy Sunday include that made you laugh?" },
  { category: "Fun", question: "What would our ideal lazy Sunday include?" },
  { category: "Fun", question: "What photo scavenger hunt theme should we do that made you tear up?" },
  { category: "Fun", question: "What photo scavenger hunt theme should we do?" },
  { category: "Fun", question: "What dessert should we bake or order together from this year?" },
  { category: "Fun", question: "What dessert should we bake or order together?" },
  { category: "Fun", question: "What outdoor activity suits us best from our first year?" },
  { category: "Fun", question: "What outdoor activity suits us best?" },
  { category: "Fun", question: "What would a themed date night look like for us that we should do more often?" },
  { category: "Fun", question: "What would a themed date night look like for us?" },
  { category: "Fun", question: "What concert or live event should we see that we should talk about tonight?" },
  { category: "Fun", question: "What concert or live event should we see?" },
  { category: "Fun", question: "What mini road trip could we take this weekend that would strengthen us?" },
  { category: "Fun", question: "What mini road trip could we take this weekend?" },
  { category: "Fun", question: "What couple bucket-list item should we tackle next that feels uniquely us?" },
  { category: "Fun", question: "What couple bucket-list item should we tackle next?" },
  { category: "Gratitude", question: "What did I do this week that you are grateful for that you have never told anyone?" },
  { category: "Gratitude", question: "What did I do this week that you are grateful for?" },
  { category: "Gratitude", question: "What quality of mine are you thankful for today that you want more of?" },
  { category: "Gratitude", question: "What quality of mine are you thankful for today?" },
  { category: "Gratitude", question: "What sacrifice of mine have you noticed lately right now?" },
  { category: "Gratitude", question: "What sacrifice of mine have you noticed lately?" },
  { category: "Gratitude", question: "What support from me meant the most recently this season?" },
  { category: "Gratitude", question: "What support from me meant the most recently?" },
  { category: "Gratitude", question: "What everyday thing I do makes your life easier before we met?" },
  { category: "Gratitude", question: "What everyday thing I do makes your life easier?" },
  { category: "Gratitude", question: "What lesson from me are you glad you learned on our worst day?" },
  { category: "Gratitude", question: "What lesson from me are you glad you learned?" },
  { category: "Gratitude", question: "What moment this month are you glad we shared on our best day?" },
  { category: "Gratitude", question: "What moment this month are you glad we shared?" },
  { category: "Gratitude", question: "What way do I show up for you that you appreciate when we are apart?" },
  { category: "Gratitude", question: "What way do I show up for you that you appreciate?" },
  { category: "Gratitude", question: "What kindness from me surprised you when we are together?" },
  { category: "Gratitude", question: "What kindness from me surprised you?" },
  { category: "Gratitude", question: "What about our routine together are you grateful for that we have not tried yet?" },
  { category: "Gratitude", question: "What about our routine together are you grateful for?" },
  { category: "Gratitude", question: "What did I say recently that stuck with you that nobody else knows?" },
  { category: "Gratitude", question: "What did I say recently that stuck with you?" },
  { category: "Gratitude", question: "What effort of mine do you want to acknowledge that still surprises you?" },
  { category: "Gratitude", question: "What effort of mine do you want to acknowledge?" },
  { category: "Gratitude", question: "What memory with me are you thankful exists that made you laugh?" },
  { category: "Gratitude", question: "What memory with me are you thankful exists?" },
  { category: "Gratitude", question: "What part of how I love you feels like a gift that made you tear up?" },
  { category: "Gratitude", question: "What part of how I love you feels like a gift?" },
  { category: "Gratitude", question: "What would you thank me for if I were sitting here from this year?" },
  { category: "Gratitude", question: "What would you thank me for if I were sitting here?" },
  { category: "Gratitude", question: "What patience from me are you grateful for from our first year?" },
  { category: "Gratitude", question: "What patience from me are you grateful for?" },
  { category: "Gratitude", question: "What laugh with me are you glad you had that we should do more often?" },
  { category: "Gratitude", question: "What laugh with me are you glad you had?" },
  { category: "Gratitude", question: "What comfort from me helped you recently that we should talk about tonight?" },
  { category: "Gratitude", question: "What comfort from me helped you recently?" },
  { category: "Gratitude", question: "What dream of ours are you grateful we share that would strengthen us?" },
  { category: "Gratitude", question: "What dream of ours are you grateful we share?" },
  { category: "Gratitude", question: "What small detail about me makes you feel lucky that feels uniquely us?" },
  { category: "Gratitude", question: "What small detail about me makes you feel lucky?" },
  { category: "Future", question: "What goal should we set for the next six months that you have never told anyone?" },
  { category: "Future", question: "What goal should we set for the next six months?" },
  { category: "Future", question: "What home detail do you imagine for us someday that you want more of?" },
  { category: "Future", question: "What home detail do you imagine for us someday?" },
  { category: "Future", question: "What holiday tradition should we start right now?" },
  { category: "Future", question: "What holiday tradition should we start?" },
  { category: "Future", question: "What milestone are you excited to reach together this season?" },
  { category: "Future", question: "What milestone are you excited to reach together?" },
  { category: "Future", question: "What skill should we learn as a couple before we met?" },
  { category: "Future", question: "What skill should we learn as a couple?" },
  { category: "Future", question: "What trip is at the top of our future list on our worst day?" },
  { category: "Future", question: "What trip is at the top of our future list?" },
  { category: "Future", question: "What financial or life goal should we align on on our best day?" },
  { category: "Future", question: "What financial or life goal should we align on?" },
  { category: "Future", question: "What does your ideal anniversary look like when we are apart?" },
  { category: "Future", question: "What does your ideal anniversary look like?" },
  { category: "Future", question: "What role do you want us to play in each other's careers when we are together?" },
  { category: "Future", question: "What role do you want us to play in each other's careers?" },
  { category: "Future", question: "What family or friend tradition should we adopt that we have not tried yet?" },
  { category: "Future", question: "What family or friend tradition should we adopt?" },
  { category: "Future", question: "What does retirement together look like in your head that nobody else knows?" },
  { category: "Future", question: "What does retirement together look like in your head?" },
  { category: "Future", question: "What city could you see us living in someday that still surprises you?" },
  { category: "Future", question: "What city could you see us living in someday?" },
  { category: "Future", question: "What project should we build together this year that made you laugh?" },
  { category: "Future", question: "What project should we build together this year?" },
  { category: "Future", question: "What celebration do you want us to plan ahead for that made you tear up?" },
  { category: "Future", question: "What celebration do you want us to plan ahead for?" },
  { category: "Future", question: "What value should guide our next chapter from this year?" },
  { category: "Future", question: "What value should guide our next chapter?" },
  { category: "Future", question: "What habit should we build for our future selves from our first year?" },
  { category: "Future", question: "What habit should we build for our future selves?" },
  { category: "Future", question: "What adventure is on your five-year couple list that we should do more often?" },
  { category: "Future", question: "What adventure is on your five-year couple list?" },
  { category: "Future", question: "What legacy do you want our relationship to leave that we should talk about tonight?" },
  { category: "Future", question: "What season of life are you most excited to share that would strengthen us?" },
  { category: "Future", question: "What season of life are you most excited to share?" },
  { category: "Future", question: "What promise for our future matters most to you that feels uniquely us?" },
  { category: "Future", question: "What promise for our future matters most to you?" },
  { category: "Deep", question: "What emotion do you feel most often when you think about us that feels uniquely us?" },
  { category: "Deep", question: "What part of our relationship do you want to nurture more that you have never told anyone?" },
  { category: "Deep", question: "When do you feel most like yourself around me that you want more of?" },
  { category: "Deep", question: "What fear about love have I helped you release right now?" },
  { category: "Deep", question: "What do you need from me on hard days this season?" },
  { category: "Deep", question: "What belief about relationships has changed since we met before we met?" },
  { category: "Deep", question: "What moment made you trust me more on our worst day?" },
  { category: "Deep", question: "What do you wish we talked about more openly on our best day?" },
  { category: "Deep", question: "How do you know when you need space versus closeness when we are apart?" },
  { category: "Deep", question: "What does emotional intimacy look like for you when we are together?" },
  { category: "Deep", question: "What pattern in our relationship would you like to improve that we have not tried yet?" },
  { category: "Deep", question: "When did you last feel vulnerable with me — and how did I respond that nobody else knows?" },
  { category: "Deep", question: "What childhood lesson about love still affects you today that still surprises you?" },
  { category: "Deep", question: "What makes you feel chosen by me that made you laugh?" },
  { category: "Deep", question: "What is one thing you are still learning about me that made you tear up?" },
  { category: "Deep", question: "How has our love changed the way you see yourself from this year?" },
  { category: "Deep", question: "What do you need to hear from me more often from our first year?" },
  { category: "Deep", question: "What conflict taught us something valuable that we should do more often?" },
  { category: "Deep", question: "What does forgiveness mean in our relationship that we should talk about tonight?" },
  { category: "Deep", question: "What boundary has made us stronger that would strengthen us?" },
  { category: "Funny", question: "What is the most ridiculous thing we have argued about that feels uniquely us?" },
  { category: "Funny", question: "If we had a couple mascot, what would it be that you have never told anyone?" },
  { category: "Funny", question: "What habit of mine would be a viral TikTok trend that you want more of?" },
  { category: "Funny", question: "What would our pet say about us if it could talk right now?" },
  { category: "Funny", question: "What is my most dramatic reaction to something small this season?" },
  { category: "Funny", question: "If we starred in a rom-com, what would the plot twist be before we met?" },
  { category: "Funny", question: "What is the weirdest compliment I have given you on our worst day?" },
  { category: "Funny", question: "What would our couple merch line sell on our best day?" },
  { category: "Funny", question: "What inside joke should be on a T-shirt when we are apart?" },
  { category: "Funny", question: "What is my go-to excuse when I am running late when we are together?" },
  { category: "Funny", question: "If we swapped phones for an hour, what would shock you that we have not tried yet?" },
  { category: "Funny", question: "What is the most chaotic date we have ever had that nobody else knows?" },
  { category: "Funny", question: "What would our couple group chat name be that still surprises you?" },
  { category: "Funny", question: "What song would play when we enter a room that made you laugh?" },
  { category: "Funny", question: "What is my most predictable order at a restaurant that made you tear up?" },
  { category: "Funny", question: "If we had a couple catchphrase, what is it from this year?" },
  { category: "Funny", question: "What would a documentary about us be titled from our first year?" },
  { category: "Funny", question: "What is the funniest face I make without realizing that we should do more often?" },
  { category: "Funny", question: "What would our couple Halloween couple costume be this year that we should talk about tonight?" },
  { category: "Funny", question: "What is the most \"main character\" thing I have done that would strengthen us?" },
  { category: "Romantic", question: "What small moment with me still gives you butterflies that feels uniquely us?" },
  { category: "Romantic", question: "What gesture from me feels most romantic that you have never told anyone?" },
  { category: "Romantic", question: "When did you first picture a future with me that you want more of?" },
  { category: "Romantic", question: "What scent or song instantly reminds you of us right now?" },
  { category: "Romantic", question: "What is your favorite way we say goodbye this season?" },
  { category: "Romantic", question: "What date with me do you want to recreate before we met?" },
  { category: "Romantic", question: "What do I do that makes you feel adored on our worst day?" },
  { category: "Romantic", question: "What is the most romantic thing I have ever said on our best day?" },
  { category: "Romantic", question: "What would your ideal slow morning with me look like when we are apart?" },
  { category: "Romantic", question: "What detail about me do you find irresistibly charming when we are together?" },
  { category: "Romantic", question: "What love note would you want to find from me that we have not tried yet?" },
  { category: "Romantic", question: "What moment made you think \"I am lucky\" that nobody else knows?" },
  { category: "Romantic", question: "What is your favorite photo of us and why that still surprises you?" },
  { category: "Romantic", question: "What would a perfect kiss-from-me moment be right now that made you laugh?" },
  { category: "Romantic", question: "What tradition would make our relationship feel more romantic that made you tear up?" },
  { category: "Romantic", question: "What compliment from me do you replay in your head from this year?" },
  { category: "Romantic", question: "What do you love about the way I look at you from our first year?" },
  { category: "Romantic", question: "What surprise from me would melt your heart today that we should do more often?" },
  { category: "Romantic", question: "What is the sweetest thing we do without planning it that we should talk about tonight?" },
  { category: "Romantic", question: "What promise would you like us to make to each other that would strengthen us?" },
  { category: "Fun", question: "What adventure should we plan for next month that feels uniquely us?" },
  { category: "Fun", question: "What game should we play on our next date night that you have never told anyone?" },
  { category: "Fun", question: "What new food should we try together that you want more of?" },
  { category: "Fun", question: "What hobby could we pick up as a team right now?" },
  { category: "Fun", question: "What road trip playlist song is 100% us this season?" },
  { category: "Fun", question: "What would our dream game night include before we met?" },
  { category: "Fun", question: "What sport or activity should we learn together on our worst day?" },
  { category: "Fun", question: "What city should we explore on a weekend trip on our best day?" },
  { category: "Fun", question: "What challenge should we do as a couple this week when we are apart?" },
  { category: "Fun", question: "What show should we start watching tonight when we are together?" },
  { category: "Fun", question: "What silly competition should we have that we have not tried yet?" },
  { category: "Fun", question: "What festival or event should we attend together that nobody else knows?" },
  { category: "Fun", question: "What would our ideal lazy Sunday include that still surprises you?" },
  { category: "Fun", question: "What photo scavenger hunt theme should we do that made you laugh?" },
  { category: "Fun", question: "What dessert should we bake or order together that made you tear up?" },
  { category: "Fun", question: "What outdoor activity suits us best from this year?" },
  { category: "Fun", question: "What would a themed date night look like for us from our first year?" },
  { category: "Fun", question: "What concert or live event should we see that we should do more often?" },
  { category: "Fun", question: "What mini road trip could we take this weekend that we should talk about tonight?" },
  { category: "Fun", question: "What couple bucket-list item should we tackle next that would strengthen us?" },
  { category: "Gratitude", question: "What did I do this week that you are grateful for that feels uniquely us?" },
  { category: "Gratitude", question: "What quality of mine are you thankful for today that you have never told anyone?" },
  { category: "Gratitude", question: "What sacrifice of mine have you noticed lately that you want more of?" },
  { category: "Gratitude", question: "What support from me meant the most recently right now?" },
  { category: "Gratitude", question: "What everyday thing I do makes your life easier this season?" },
  { category: "Gratitude", question: "What lesson from me are you glad you learned before we met?" },
  { category: "Gratitude", question: "What moment this month are you glad we shared on our worst day?" },
  { category: "Gratitude", question: "What way do I show up for you that you appreciate on our best day?" },
  { category: "Gratitude", question: "What kindness from me surprised you when we are apart?" },
  { category: "Gratitude", question: "What about our routine together are you grateful for when we are together?" },
  { category: "Gratitude", question: "What did I say recently that stuck with you that we have not tried yet?" },
  { category: "Gratitude", question: "What effort of mine do you want to acknowledge that nobody else knows?" },
  { category: "Gratitude", question: "What memory with me are you thankful exists that still surprises you?" },
  { category: "Gratitude", question: "What part of how I love you feels like a gift that made you laugh?" },
  { category: "Gratitude", question: "What would you thank me for if I were sitting here that made you tear up?" },
  { category: "Gratitude", question: "What patience from me are you grateful for from this year?" },
  { category: "Gratitude", question: "What laugh with me are you glad you had from our first year?" },
  { category: "Gratitude", question: "What comfort from me helped you recently that we should do more often?" },
  { category: "Gratitude", question: "What dream of ours are you grateful we share that we should talk about tonight?" },
  { category: "Gratitude", question: "What small detail about me makes you feel lucky that would strengthen us?" },
  { category: "Future", question: "What goal should we set for the next six months that feels uniquely us?" },
  { category: "Future", question: "What home detail do you imagine for us someday that you have never told anyone?" },
  { category: "Future", question: "What holiday tradition should we start that you want more of?" },
  { category: "Future", question: "What milestone are you excited to reach together right now?" },
  { category: "Future", question: "What skill should we learn as a couple this season?" },
  { category: "Future", question: "What trip is at the top of our future list before we met?" },
  { category: "Future", question: "What financial or life goal should we align on on our worst day?" },
  { category: "Future", question: "What does your ideal anniversary look like on our best day?" },
  { category: "Future", question: "What role do you want us to play in each other's careers when we are apart?" },
  { category: "Future", question: "What family or friend tradition should we adopt when we are together?" },
  { category: "Future", question: "What does retirement together look like in your head that we have not tried yet?" },
  { category: "Future", question: "What city could you see us living in someday that nobody else knows?" },
  { category: "Future", question: "What project should we build together this year that still surprises you?" },
  { category: "Future", question: "What celebration do you want us to plan ahead for that made you laugh?" },
  { category: "Future", question: "What value should guide our next chapter that made you tear up?" },
  { category: "Future", question: "What habit should we build for our future selves from this year?" },
  { category: "Future", question: "What adventure is on your five-year couple list from our first year?" },
  { category: "Future", question: "What legacy do you want our relationship to leave that we should do more often?" },
  { category: "Future", question: "What season of life are you most excited to share that we should talk about tonight?" },
  { category: "Future", question: "What promise for our future matters most to you that would strengthen us?" },
  { category: "Deep", question: "What's one thing about communication you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about trust you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about conflict you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about affection you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about quality time you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about humor you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about support you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about ambition you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about family you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about friendships you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about travel you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about food you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about music you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about movies you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about weekends you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about mornings you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about bedtime routines you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about texting you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about surprises you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about apologies you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about celebrations you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about stress you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about success you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about failure you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about patience you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about boundaries you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about intimacy you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about adventure you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about home life you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about date nights you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about inside jokes you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about compliments you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about listening you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about teamwork you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about finances you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about health you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about fitness you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about creativity you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about learning you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about traditions you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about holidays you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about gifts you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about kindness you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about forgiveness you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about loyalty you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about flirting you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about cuddling you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about cooking you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about cleaning you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about planning you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about spontaneity you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about social life you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about alone time you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about phone habits you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about sleep you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about dreams you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about memories you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about first dates you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about anniversaries you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about road trips you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about pets you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about future plans you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about careers you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about gratitude you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about vulnerability you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about laughter you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about reassurance you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about jealousy you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about space you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about closeness you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about routine you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about change you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about growth you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about values you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about faith you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about community you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about volunteering you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about photography you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about dancing you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about singing you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about gaming you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about reading you've been thinking about lately?" },
  { category: "Deep", question: "What's one thing about writing you've been thinking about lately?" },
];
