// 78 daily prompts — ~11 weeks before the same question returns (day-of-year rotation).
export const DAILY_QUESTIONS_CATALOG = [
  { category: 'Deep', question: "What's one small thing I do that makes you feel loved?" },
  { category: 'Funny', question: 'If we switched bodies for a day, what would you do first?' },
  { category: 'Deep', question: "What's your favorite memory of us from this month?" },
  { category: 'Romantic', question: 'What song reminds you of our relationship?' },
  { category: 'Fun', question: 'If we could teleport anywhere right now, where would we go?' },
  { category: 'Deep', question: "What's something new you'd love to try together?" },
  { category: 'Funny', question: 'What is the most "us" thing we do without trying?' },
  { category: 'Romantic', question: 'When did you first know you were falling for me?' },
  { category: 'Fun', question: 'What would our couple superpower be?' },
  { category: 'Deep', question: 'What do you need more of from me this week?' },
  { category: 'Gratitude', question: 'What did I do recently that you appreciated but never said thank you for?' },
  { category: 'Future', question: 'Where do you see us in five years — be specific.' },
  { category: 'Romantic', question: 'What was your first impression of me, honestly?' },
  { category: 'Funny', question: 'What\'s the dumbest argument we\'ve ever had?' },
  { category: 'Deep', question: 'When do you feel most emotionally connected to me?' },
  { category: 'Fun', question: 'If we had a free weekend with no plans, what would we do?' },
  { category: 'Gratitude', question: 'What quality of mine are you most grateful for right now?' },
  { category: 'Future', question: 'What\'s one tradition you want us to start as a couple?' },
  { category: 'Romantic', question: 'What\'s your favorite way I show affection?' },
  { category: 'Deep', question: 'What\'s something you\'ve been holding back that you want to share?' },
  { category: 'Funny', question: 'What would our reality show be called?' },
  { category: 'Fun', question: 'What\'s a hobby we should pick up together?' },
  { category: 'Deep', question: 'How has being with me changed you?' },
  { category: 'Romantic', question: 'Describe our relationship in three words.' },
  { category: 'Future', question: 'What\'s on your couple bucket list that we haven\'t done yet?' },
  { category: 'Gratitude', question: 'What\'s a hard moment we got through that made us stronger?' },
  { category: 'Funny', question: 'Who would play us in a movie about our relationship?' },
  { category: 'Deep', question: 'What makes you feel safe with me?' },
  { category: 'Fun', question: 'What\'s the best meal we\'ve ever shared?' },
  { category: 'Romantic', question: 'What\'s a moment with me you replay in your head?' },
  { category: 'Future', question: 'How do you want us to celebrate our next anniversary?' },
  { category: 'Deep', question: 'What\'s one thing you wish I understood better about you?' },
  { category: 'Gratitude', question: 'When did you last feel proud to be my partner?' },
  { category: 'Funny', question: 'What\'s my most predictable habit — and do you secretly love it?' },
  { category: 'Fun', question: 'If we opened a business together, what would it be?' },
  { category: 'Romantic', question: 'What\'s the sweetest text I\'ve ever sent you?' },
  { category: 'Deep', question: 'What does "home" mean to you — and am I part of it?' },
  { category: 'Future', question: 'What\'s one goal you want us to work toward this year?' },
  { category: 'Gratitude', question: 'What\'s something I do that always cheers you up?' },
  { category: 'Funny', question: 'What would our couple Halloween costume be?' },
  { category: 'Deep', question: 'What\'s your love language — and how can I speak it better?' },
  { category: 'Romantic', question: 'What\'s your favorite photo of us and why?' },
  { category: 'Fun', question: 'What game or activity should we do on our next date night?' },
  { category: 'Future', question: 'Where do you want to travel together next?' },
  { category: 'Deep', question: 'What\'s a fear you have about relationships that I can help ease?' },
  { category: 'Gratitude', question: 'What\'s the best advice I\'ve ever given you?' },
  { category: 'Funny', question: 'What\'s my tell when I\'m in a bad mood?' },
  { category: 'Romantic', question: 'What small gesture from me means the most?' },
  { category: 'Deep', question: 'When was the last time you felt truly seen by me?' },
  { category: 'Fun', question: 'What\'s a show we should binge-watch together?' },
  { category: 'Future', question: 'Do you want kids, pets, or neither — and how do we align?' },
  { category: 'Gratitude', question: 'What\'s one way I\'ve helped you grow?' },
  { category: 'Funny', question: 'What\'s the weirdest food combo I\'ve convinced you to try?' },
  { category: 'Deep', question: 'What\'s your ideal balance of together time vs. alone time?' },
  { category: 'Romantic', question: 'What\'s a date idea we\'ve never done but should?' },
  { category: 'Fun', question: 'If we won a free vacation tomorrow, where are we going?' },
  { category: 'Future', question: 'What does your dream weekend with me look like?' },
  { category: 'Deep', question: 'What\'s something you admire about how I handle stress?' },
  { category: 'Gratitude', question: 'What\'s a sacrifice I\'ve made for us that you noticed?' },
  { category: 'Funny', question: 'What nickname for me do you use when I\'m not around?' },
  { category: 'Romantic', question: 'What\'s your favorite "ordinary" moment with me?' },
  { category: 'Deep', question: 'How do you prefer we resolve disagreements?' },
  { category: 'Fun', question: 'What\'s a playlist song that is 100% us?' },
  { category: 'Future', question: 'What kind of home do you imagine us living in someday?' },
  { category: 'Gratitude', question: 'What made you choose me?' },
  { category: 'Funny', question: 'What\'s the most embarrassing thing I\'ve done in front of you?' },
  { category: 'Deep', question: 'What\'s one boundary that helps our relationship thrive?' },
  { category: 'Romantic', question: 'When do you feel most attracted to me — and why?' },
  { category: 'Fun', question: 'What\'s a challenge we should tackle as a team this month?' },
  { category: 'Future', question: 'What legacy do you want our relationship to leave?' },
  { category: 'Deep', question: 'What\'s one thing you want to forgive or let go of between us?' },
  { category: 'Gratitude', question: 'What\'s the best compliment I\'ve ever given you?' },
  { category: 'Funny', question: 'If we were characters in a sitcom, who\'d be the funny one?' },
  { category: 'Romantic', question: 'What\'s one thing I do that still gives you butterflies?' },
  { category: 'Deep', question: 'What does commitment mean to you in our relationship?' },
  { category: 'Fun', question: 'What\'s a silly tradition we should invent today?' },
  { category: 'Future', question: 'What\'s one skill you want us to learn together?' },
  { category: 'Gratitude', question: 'What\'s one thing about today you\'re glad we shared?' },
];
