// 520 dares — ~17 months before the same dare returns.
export const DARE_CATALOG = [
  {
    id: "dare-1",
    text: "Send your partner a voice note saying three things you love about them",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-2",
    text: "Plan a 15-minute surprise for your partner today",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-3",
    text: "Write a handwritten note and hide it somewhere they'll find it",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-4",
    text: "Pick a song that describes your partner and share why",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-5",
    text: "Give your partner a 60-second compliment marathon",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-6",
    text: "Pick up their favorite drink and leave it with a sweet note",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-7",
    text: "Text them your favorite memory together and why it still matters",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-8",
    text: "Start a two-song kitchen dance party when you see them next",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-9",
    text: "Make or order their favorite breakfast and surprise them with it",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-10",
    text: "Send them 3 photos that remind you of them throughout the day",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-11",
    text: "Write a list of 10 things you're grateful for about your partner",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-12",
    text: "Spend one hour together with phones put away — just talk or cuddle",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-13",
    text: "Create a 5-song playlist just for them and share it",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-14",
    text: "Take one thing off their to-do list without being asked",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-15",
    text: "Write a short love letter and read it aloud to them",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-16",
    text: "Record a silly 15-second video telling them why they're amazing",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-17",
    text: "Stock up on their favorite snack and leave it where they'll find it",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-18",
    text: "Suggest a 20-minute walk together with no destination",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-19",
    text: "Share your favorite photo of the two of you and the story behind it",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-20",
    text: "Offer a 10-minute shoulder or back massage — no strings attached",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-21",
    text: "Plan a full date night for this week and tell them the surprise details",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-22",
    text: "Compliment them in front of a friend or family member today",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-23",
    text: "Pick a recipe and cook one meal together tonight",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-24",
    text: "Recreate an inside joke or memory in a funny way and send it to them",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-25",
    text: "Tell them one specific dream you have for your future together",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-26",
    text: "Do one of their usual chores today without mentioning it first",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-27",
    text: "Step outside tonight and look at the sky together for 10 minutes",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-28",
    text: "Ask them about their day, then share your favorite moment from it",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-29",
    text: "If something's been unresolved, apologize sincerely and name one change you'll make",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-30",
    text: "Call them just to say hi — no agenda, no asking for anything",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-31",
    text: "Recommend something (book, show, article) that made you think of them",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-32",
    text: "Research one new place to explore together and pitch it to them",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-33",
    text: "Send your partner a voice note about something you admire about them without explaining why first",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-34",
    text: "Send your partner a voice note about something you admire about them",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-35",
    text: "Write a sticky note with a compliment and put it where they will find it and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-36",
    text: "Write a sticky note with a compliment and put it where they will find it",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-37",
    text: "Pick a song that reminds you of them and share why with a specific detail from this week",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-38",
    text: "Pick a song that reminds you of them and share why",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-39",
    text: "Plan a surprise snack or drink for them today using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-40",
    text: "Plan a surprise snack or drink for them today",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-41",
    text: "Text them three things you are grateful for about your relationship and include one thing you have never said",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-42",
    text: "Text them three things you are grateful for about your relationship",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-43",
    text: "Offer to handle one chore they usually do in person if possible",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-44",
    text: "Offer to handle one chore they usually do",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-45",
    text: "Record a 15-second video saying something sweet as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-46",
    text: "Record a 15-second video saying something sweet",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-47",
    text: "Suggest a walk together with no phones and follow up with a hug",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-48",
    text: "Suggest a walk together with no phones",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-49",
    text: "Share your favorite photo of the two of you and the story behind it before bed",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-50",
    text: "Leave a handwritten note in their bag or pocket when they least expect it",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-51",
    text: "Leave a handwritten note in their bag or pocket",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-52",
    text: "Make or order their favorite comfort food without explaining why first",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-53",
    text: "Make or order their favorite comfort food",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-54",
    text: "Compliment them in front of someone else today and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-55",
    text: "Compliment them in front of someone else today",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-56",
    text: "Create a short playlist of songs that remind you of them with a specific detail from this week",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-57",
    text: "Create a short playlist of songs that remind you of them",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-58",
    text: "Tell them one specific dream you have for your future together using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-59",
    text: "Do something kind for them before they ask and include one thing you have never said",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-60",
    text: "Do something kind for them before they ask",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-61",
    text: "Send them a meme that made you think of them in person if possible",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-62",
    text: "Send them a meme that made you think of them",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-63",
    text: "Plan a low-key date for this week and share the details as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-64",
    text: "Plan a low-key date for this week and share the details",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-65",
    text: "Give them a genuine 60-second compliment and follow up with a hug",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-66",
    text: "Give them a genuine 60-second compliment",
    category: "Right Now",
    timeEstimate: "25 min",
  },
  {
    id: "dare-67",
    text: "Apologize for something small you have been holding onto before bed",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-68",
    text: "Apologize for something small you have been holding onto",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-69",
    text: "Call them just to say you are thinking of them when they least expect it",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-70",
    text: "Call them just to say you are thinking of them",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-71",
    text: "Hide a small treat where they will discover it without explaining why first",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-72",
    text: "Hide a small treat where they will discover it",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-73",
    text: "Share a memory from this month that you loved and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-74",
    text: "Share a memory from this month that you loved",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-75",
    text: "Offer a shoulder rub or hug with no strings attached with a specific detail from this week",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-76",
    text: "Offer a shoulder rub or hug with no strings attached",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-77",
    text: "Text them what you love about their laugh using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-78",
    text: "Text them what you love about their laugh",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-79",
    text: "Research one new place to explore together and pitch it and include one thing you have never said",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-80",
    text: "Research one new place to explore together and pitch it",
    category: "This Week",
    timeEstimate: "45 min",
  },
  {
    id: "dare-81",
    text: "Recreate a favorite date idea in a small way in person if possible",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-82",
    text: "Recreate a favorite date idea in a small way",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-83",
    text: "Tell them what you noticed about them today as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-84",
    text: "Tell them what you noticed about them today",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-85",
    text: "Write a list of five reasons you are glad you are together and follow up with a hug",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-86",
    text: "Write a list of five reasons you are glad you are together",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-87",
    text: "Send a photo of something that reminded you of them before bed",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-88",
    text: "Send a photo of something that reminded you of them",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-89",
    text: "Suggest cooking one meal together tonight when they least expect it",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-90",
    text: "Suggest cooking one meal together tonight",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-91",
    text: "Share one thing they do that makes you feel safe without explaining why first",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-92",
    text: "Share one thing they do that makes you feel safe",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-93",
    text: "Plan a movie night with their favorite genre and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-94",
    text: "Plan a movie night with their favorite genre",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-95",
    text: "Leave a sweet message on their mirror or fridge with a specific detail from this week",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-96",
    text: "Leave a sweet message on their mirror or fridge",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-97",
    text: "Tell them about a moment you felt proud to be their partner using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-98",
    text: "Tell them about a moment you felt proud to be their partner",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-99",
    text: "Do a random act of kindness for them today and include one thing you have never said",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-100",
    text: "Do a random act of kindness for them today",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-101",
    text: "Share a book, show, or article that made you think of them in person if possible",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-102",
    text: "Share a book, show, or article that made you think of them",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-103",
    text: "Start a two-song dance when you see them next as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-104",
    text: "Start a two-song dance when you see them next",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-105",
    text: "Text them your favorite inside joke and follow up with a hug",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-106",
    text: "Text them your favorite inside joke",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-107",
    text: "Offer to run an errand they have been putting off before bed",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-108",
    text: "Offer to run an errand they have been putting off",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-109",
    text: "Tell them one thing you want to do together this month when they least expect it",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-110",
    text: "Tell them one thing you want to do together this month",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-111",
    text: "Send your partner a voice note about something you admire about them before bed",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-112",
    text: "Write a sticky note with a compliment and put it where they will find it when they least expect it",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-113",
    text: "Pick a song that reminds you of them and share why without explaining why first",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-114",
    text: "Plan a surprise snack or drink for them today and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-115",
    text: "Text them three things you are grateful for about your relationship with a specific detail from this week",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-116",
    text: "Offer to handle one chore they usually do using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-117",
    text: "Record a 15-second video saying something sweet and include one thing you have never said",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-118",
    text: "Suggest a walk together with no phones in person if possible",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-119",
    text: "Share your favorite photo of the two of you and the story behind it as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-120",
    text: "Leave a handwritten note in their bag or pocket and follow up with a hug",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-121",
    text: "Make or order their favorite comfort food before bed",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-122",
    text: "Compliment them in front of someone else today when they least expect it",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-123",
    text: "Create a short playlist of songs that remind you of them without explaining why first",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-124",
    text: "Tell them one specific dream you have for your future together and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-125",
    text: "Do something kind for them before they ask with a specific detail from this week",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-126",
    text: "Send them a meme that made you think of them using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-127",
    text: "Plan a low-key date for this week and share the details and include one thing you have never said",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-128",
    text: "Give them a genuine 60-second compliment in person if possible",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-129",
    text: "Apologize for something small you have been holding onto as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-130",
    text: "Call them just to say you are thinking of them and follow up with a hug",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-131",
    text: "Hide a small treat where they will discover it before bed",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-132",
    text: "Share a memory from this month that you loved when they least expect it",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-133",
    text: "Offer a shoulder rub or hug with no strings attached without explaining why first",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-134",
    text: "Text them what you love about their laugh and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-135",
    text: "Research one new place to explore together and pitch it with a specific detail from this week",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-136",
    text: "Recreate a favorite date idea in a small way using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-137",
    text: "Tell them what you noticed about them today and include one thing you have never said",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-138",
    text: "Write a list of five reasons you are glad you are together in person if possible",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-139",
    text: "Send a photo of something that reminded you of them as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-140",
    text: "Suggest cooking one meal together tonight and follow up with a hug",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-141",
    text: "Share one thing they do that makes you feel safe before bed",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-142",
    text: "Plan a movie night with their favorite genre when they least expect it",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-143",
    text: "Leave a sweet message on their mirror or fridge without explaining why first",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-144",
    text: "Tell them about a moment you felt proud to be their partner and read it aloud if you can",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-145",
    text: "Do a random act of kindness for them today with a specific detail from this week",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-146",
    text: "Share a book, show, or article that made you think of them using only emojis first, then explain",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-147",
    text: "Start a two-song dance when you see them next and include one thing you have never said",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-148",
    text: "Text them your favorite inside joke in person if possible",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-149",
    text: "Offer to run an errand they have been putting off as a surprise mid-day",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-150",
    text: "Tell them one thing you want to do together this month and follow up with a hug",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-151",
    text: "Send your partner a voice note about something you admire about them today",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-152",
    text: "Send your partner a voice note about your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-153",
    text: "Send your partner a voice note about three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "8 min",
  },
  {
    id: "dare-154",
    text: "Send your partner a voice note about a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-155",
    text: "Send your partner a voice note about a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-156",
    text: "Send your partner a voice note about a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-157",
    text: "Send your partner a voice note about a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-158",
    text: "Send your partner a voice note about something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-159",
    text: "Send your partner a voice note about your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-160",
    text: "Send your partner a voice note about a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-161",
    text: "Send your partner a voice note about what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-162",
    text: "Send your partner a voice note about a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-163",
    text: "Send your partner a voice note about a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-164",
    text: "Send your partner a voice note about how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-165",
    text: "Send your partner a voice note about a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-166",
    text: "Send your partner a voice note about something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-167",
    text: "Send your partner a voice note about a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-168",
    text: "Send your partner a voice note about what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-169",
    text: "Send your partner a voice note about a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-170",
    text: "Send your partner a voice note about a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-171",
    text: "Send your partner a voice note about their kindness to others today",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-172",
    text: "Send your partner a voice note about how they handle stress before bed",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-173",
    text: "Send your partner a voice note about a meal you want to share when you see them next",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-174",
    text: "Send your partner a voice note about a place you want to visit together this week",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-175",
    text: "Send your partner a voice note about a show you want to watch together without telling them first",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-176",
    text: "Send your partner a voice note about a challenge you want to tackle as a team with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-177",
    text: "Send your partner a voice note about a tradition to start in person if you can",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-178",
    text: "Send your partner a voice note about a book or article that made you think of them as a mid-day surprise",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-179",
    text: "Send your partner a voice note about what you are rooting for them on and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-180",
    text: "Send your partner a voice note about a silly moment you loved and read it aloud if possible",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-181",
    text: "Send your partner a voice note about their patience with you today",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-182",
    text: "Send your partner a voice note about a gift idea \"just because\" before bed",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-183",
    text: "Send your partner a voice note about a hug they gave that you remember when you see them next",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-184",
    text: "Send your partner a voice note about a goal you want to support this week",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-185",
    text: "Send your partner a voice note about a fear you want to ease for them without telling them first",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-186",
    text: "Send your partner a voice note about a moment they made you laugh with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-187",
    text: "Send your partner a voice note about how they show love in small ways in person if you can",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-188",
    text: "Send your partner a voice note about a photo scavenger hunt theme as a mid-day surprise",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-189",
    text: "Send your partner a voice note about a playlist for a road trip and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-190",
    text: "Send your partner a voice note about a handwritten letter and read it aloud if possible",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-191",
    text: "Send your partner a voice note about a breakfast surprise today",
    category: "Right Now",
    timeEstimate: "25 min",
  },
  {
    id: "dare-192",
    text: "Send your partner a voice note about a chore you can take off their plate before bed",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-193",
    text: "Send your partner a voice note about a cozy night in plan when you see them next",
    category: "This Week",
    timeEstimate: "45 min",
  },
  {
    id: "dare-194",
    text: "Send your partner a voice note about a public compliment this week",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-195",
    text: "Send your partner a voice note about a dance party in the kitchen without telling them first",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-196",
    text: "Send your partner a voice note about a stargazing moment with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-197",
    text: "Send your partner a voice note about a walk with no destination in person if you can",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-198",
    text: "Send your partner a voice note about a favorite photo and its story as a mid-day surprise",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-199",
    text: "Send your partner a voice note about a 60-second compliment marathon and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-200",
    text: "Send your partner a voice note about a thank-you for something small and read it aloud if possible",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-201",
    text: "Write a note about something you admire about them today",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-202",
    text: "Write a note about your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-203",
    text: "Write a note about three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-204",
    text: "Write a note about a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-205",
    text: "Write a note about a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-206",
    text: "Write a note about a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-207",
    text: "Write a note about a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-208",
    text: "Write a note about something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "8 min",
  },
  {
    id: "dare-209",
    text: "Write a note about your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-210",
    text: "Write a note about a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-211",
    text: "Write a note about what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-212",
    text: "Write a note about a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-213",
    text: "Write a note about a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-214",
    text: "Write a note about how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-215",
    text: "Write a note about a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-216",
    text: "Write a note about something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-217",
    text: "Write a note about a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-218",
    text: "Write a note about what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-219",
    text: "Write a note about a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-220",
    text: "Write a note about a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-221",
    text: "Write a note about their kindness to others today",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-222",
    text: "Write a note about how they handle stress before bed",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-223",
    text: "Write a note about a meal you want to share when you see them next",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-224",
    text: "Write a note about a place you want to visit together this week",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-225",
    text: "Write a note about a show you want to watch together without telling them first",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-226",
    text: "Write a note about a challenge you want to tackle as a team with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-227",
    text: "Write a note about a tradition to start in person if you can",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-228",
    text: "Write a note about a book or article that made you think of them as a mid-day surprise",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-229",
    text: "Write a note about what you are rooting for them on and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-230",
    text: "Write a note about a silly moment you loved and read it aloud if possible",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-231",
    text: "Write a note about their patience with you today",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-232",
    text: "Write a note about a gift idea \"just because\" before bed",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-233",
    text: "Write a note about a hug they gave that you remember when you see them next",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-234",
    text: "Write a note about a goal you want to support this week",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-235",
    text: "Write a note about a fear you want to ease for them without telling them first",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-236",
    text: "Write a note about a moment they made you laugh with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-237",
    text: "Write a note about how they show love in small ways in person if you can",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-238",
    text: "Write a note about a photo scavenger hunt theme as a mid-day surprise",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-239",
    text: "Write a note about a playlist for a road trip and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-240",
    text: "Write a note about a handwritten letter and read it aloud if possible",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-241",
    text: "Write a note about a breakfast surprise today",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-242",
    text: "Write a note about a chore you can take off their plate before bed",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-243",
    text: "Write a note about a cozy night in plan when you see them next",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-244",
    text: "Write a note about a public compliment this week",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-245",
    text: "Write a note about a dance party in the kitchen without telling them first",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-246",
    text: "Write a note about a stargazing moment with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "25 min",
  },
  {
    id: "dare-247",
    text: "Write a note about a walk with no destination in person if you can",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-248",
    text: "Write a note about a favorite photo and its story as a mid-day surprise",
    category: "This Week",
    timeEstimate: "45 min",
  },
  {
    id: "dare-249",
    text: "Write a note about a 60-second compliment marathon and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-250",
    text: "Write a note about a thank-you for something small and read it aloud if possible",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-251",
    text: "Text your partner about something you admire about them today",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-252",
    text: "Text your partner about your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-253",
    text: "Text your partner about three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-254",
    text: "Text your partner about a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-255",
    text: "Text your partner about a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-256",
    text: "Text your partner about a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-257",
    text: "Text your partner about a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-258",
    text: "Text your partner about something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-259",
    text: "Text your partner about your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-260",
    text: "Text your partner about a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-261",
    text: "Text your partner about what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-262",
    text: "Text your partner about a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-263",
    text: "Text your partner about a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "8 min",
  },
  {
    id: "dare-264",
    text: "Text your partner about how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-265",
    text: "Text your partner about a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-266",
    text: "Text your partner about something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-267",
    text: "Text your partner about a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-268",
    text: "Text your partner about what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-269",
    text: "Text your partner about a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-270",
    text: "Text your partner about a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-271",
    text: "Text your partner about their kindness to others today",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-272",
    text: "Text your partner about how they handle stress before bed",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-273",
    text: "Text your partner about a meal you want to share when you see them next",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-274",
    text: "Text your partner about a place you want to visit together this week",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-275",
    text: "Text your partner about a show you want to watch together without telling them first",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-276",
    text: "Text your partner about a challenge you want to tackle as a team with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-277",
    text: "Text your partner about a tradition to start in person if you can",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-278",
    text: "Text your partner about a book or article that made you think of them as a mid-day surprise",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-279",
    text: "Text your partner about what you are rooting for them on and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-280",
    text: "Text your partner about a silly moment you loved and read it aloud if possible",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-281",
    text: "Text your partner about their patience with you today",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-282",
    text: "Text your partner about a gift idea \"just because\" before bed",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-283",
    text: "Text your partner about a hug they gave that you remember when you see them next",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-284",
    text: "Text your partner about a goal you want to support this week",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-285",
    text: "Text your partner about a fear you want to ease for them without telling them first",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-286",
    text: "Text your partner about a moment they made you laugh with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-287",
    text: "Text your partner about how they show love in small ways in person if you can",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-288",
    text: "Text your partner about a photo scavenger hunt theme as a mid-day surprise",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-289",
    text: "Text your partner about a playlist for a road trip and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-290",
    text: "Text your partner about a handwritten letter and read it aloud if possible",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-291",
    text: "Text your partner about a breakfast surprise today",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-292",
    text: "Text your partner about a chore you can take off their plate before bed",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-293",
    text: "Text your partner about a cozy night in plan when you see them next",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-294",
    text: "Text your partner about a public compliment this week",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-295",
    text: "Text your partner about a dance party in the kitchen without telling them first",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-296",
    text: "Text your partner about a stargazing moment with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-297",
    text: "Text your partner about a walk with no destination in person if you can",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-298",
    text: "Text your partner about a favorite photo and its story as a mid-day surprise",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-299",
    text: "Text your partner about a 60-second compliment marathon and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-300",
    text: "Text your partner about a thank-you for something small and read it aloud if possible",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-301",
    text: "Share with your partner something you admire about them today",
    category: "Right Now",
    timeEstimate: "25 min",
  },
  {
    id: "dare-302",
    text: "Share with your partner your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-303",
    text: "Share with your partner three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "45 min",
  },
  {
    id: "dare-304",
    text: "Share with your partner a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-305",
    text: "Share with your partner a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-306",
    text: "Share with your partner a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-307",
    text: "Share with your partner a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-308",
    text: "Share with your partner something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-309",
    text: "Share with your partner your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-310",
    text: "Share with your partner a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-311",
    text: "Share with your partner what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-312",
    text: "Share with your partner a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-313",
    text: "Share with your partner a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-314",
    text: "Share with your partner how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-315",
    text: "Share with your partner a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-316",
    text: "Share with your partner something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-317",
    text: "Share with your partner a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-318",
    text: "Share with your partner what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "8 min",
  },
  {
    id: "dare-319",
    text: "Share with your partner a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-320",
    text: "Share with your partner a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-321",
    text: "Share with your partner their kindness to others today",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-322",
    text: "Share with your partner how they handle stress before bed",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-323",
    text: "Share with your partner a meal you want to share when you see them next",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-324",
    text: "Share with your partner a place you want to visit together this week",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-325",
    text: "Share with your partner a show you want to watch together without telling them first",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-326",
    text: "Share with your partner a challenge you want to tackle as a team with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-327",
    text: "Share with your partner a tradition to start in person if you can",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-328",
    text: "Share with your partner a book or article that made you think of them as a mid-day surprise",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-329",
    text: "Share with your partner what you are rooting for them on and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-330",
    text: "Share with your partner a silly moment you loved and read it aloud if possible",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-331",
    text: "Share with your partner their patience with you today",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-332",
    text: "Share with your partner a gift idea \"just because\" before bed",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-333",
    text: "Share with your partner a hug they gave that you remember when you see them next",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-334",
    text: "Share with your partner a goal you want to support this week",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-335",
    text: "Share with your partner a fear you want to ease for them without telling them first",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-336",
    text: "Share with your partner a moment they made you laugh with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-337",
    text: "Share with your partner how they show love in small ways in person if you can",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-338",
    text: "Share with your partner a photo scavenger hunt theme as a mid-day surprise",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-339",
    text: "Share with your partner a playlist for a road trip and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-340",
    text: "Share with your partner a handwritten letter and read it aloud if possible",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-341",
    text: "Share with your partner a breakfast surprise today",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-342",
    text: "Share with your partner a chore you can take off their plate before bed",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-343",
    text: "Share with your partner a cozy night in plan when you see them next",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-344",
    text: "Share with your partner a public compliment this week",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-345",
    text: "Share with your partner a dance party in the kitchen without telling them first",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-346",
    text: "Share with your partner a stargazing moment with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-347",
    text: "Share with your partner a walk with no destination in person if you can",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-348",
    text: "Share with your partner a favorite photo and its story as a mid-day surprise",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-349",
    text: "Share with your partner a 60-second compliment marathon and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-350",
    text: "Share with your partner a thank-you for something small and read it aloud if possible",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-351",
    text: "Tell your partner about something you admire about them today",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-352",
    text: "Tell your partner about your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-353",
    text: "Tell your partner about three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-354",
    text: "Tell your partner about a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-355",
    text: "Tell your partner about a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-356",
    text: "Tell your partner about a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "25 min",
  },
  {
    id: "dare-357",
    text: "Tell your partner about a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-358",
    text: "Tell your partner about something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "45 min",
  },
  {
    id: "dare-359",
    text: "Tell your partner about your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-360",
    text: "Tell your partner about a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-361",
    text: "Tell your partner about what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-362",
    text: "Tell your partner about a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-363",
    text: "Tell your partner about a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-364",
    text: "Tell your partner about how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-365",
    text: "Tell your partner about a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-366",
    text: "Tell your partner about something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-367",
    text: "Tell your partner about a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-368",
    text: "Tell your partner about what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-369",
    text: "Tell your partner about a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-370",
    text: "Tell your partner about a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-371",
    text: "Tell your partner about their kindness to others today",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-372",
    text: "Tell your partner about how they handle stress before bed",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-373",
    text: "Tell your partner about a meal you want to share when you see them next",
    category: "This Week",
    timeEstimate: "8 min",
  },
  {
    id: "dare-374",
    text: "Tell your partner about a place you want to visit together this week",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-375",
    text: "Tell your partner about a show you want to watch together without telling them first",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-376",
    text: "Tell your partner about a challenge you want to tackle as a team with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-377",
    text: "Tell your partner about a tradition to start in person if you can",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-378",
    text: "Tell your partner about a book or article that made you think of them as a mid-day surprise",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-379",
    text: "Tell your partner about what you are rooting for them on and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-380",
    text: "Tell your partner about a silly moment you loved and read it aloud if possible",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-381",
    text: "Tell your partner about their patience with you today",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-382",
    text: "Tell your partner about a gift idea \"just because\" before bed",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-383",
    text: "Tell your partner about a hug they gave that you remember when you see them next",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-384",
    text: "Tell your partner about a goal you want to support this week",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-385",
    text: "Tell your partner about a fear you want to ease for them without telling them first",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-386",
    text: "Tell your partner about a moment they made you laugh with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-387",
    text: "Tell your partner about how they show love in small ways in person if you can",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-388",
    text: "Tell your partner about a photo scavenger hunt theme as a mid-day surprise",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-389",
    text: "Tell your partner about a playlist for a road trip and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-390",
    text: "Tell your partner about a handwritten letter and read it aloud if possible",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-391",
    text: "Tell your partner about a breakfast surprise today",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-392",
    text: "Tell your partner about a chore you can take off their plate before bed",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-393",
    text: "Tell your partner about a cozy night in plan when you see them next",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-394",
    text: "Tell your partner about a public compliment this week",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-395",
    text: "Tell your partner about a dance party in the kitchen without telling them first",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-396",
    text: "Tell your partner about a stargazing moment with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-397",
    text: "Tell your partner about a walk with no destination in person if you can",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-398",
    text: "Tell your partner about a favorite photo and its story as a mid-day surprise",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-399",
    text: "Tell your partner about a 60-second compliment marathon and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-400",
    text: "Tell your partner about a thank-you for something small and read it aloud if possible",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-401",
    text: "Plan a surprise around something you admire about them today",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-402",
    text: "Plan a surprise around your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-403",
    text: "Plan a surprise around three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-404",
    text: "Plan a surprise around a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-405",
    text: "Plan a surprise around a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-406",
    text: "Plan a surprise around a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-407",
    text: "Plan a surprise around a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-408",
    text: "Plan a surprise around something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-409",
    text: "Plan a surprise around your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-410",
    text: "Plan a surprise around a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-411",
    text: "Plan a surprise around what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "25 min",
  },
  {
    id: "dare-412",
    text: "Plan a surprise around a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-413",
    text: "Plan a surprise around a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "45 min",
  },
  {
    id: "dare-414",
    text: "Plan a surprise around how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-415",
    text: "Plan a surprise around a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-416",
    text: "Plan a surprise around something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-417",
    text: "Plan a surprise around a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-418",
    text: "Plan a surprise around what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-419",
    text: "Plan a surprise around a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-420",
    text: "Plan a surprise around a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-421",
    text: "Plan a surprise around their kindness to others today",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-422",
    text: "Plan a surprise around how they handle stress before bed",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-423",
    text: "Plan a surprise around a meal you want to share when you see them next",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-424",
    text: "Plan a surprise around a place you want to visit together this week",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-425",
    text: "Plan a surprise around a show you want to watch together without telling them first",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-426",
    text: "Plan a surprise around a challenge you want to tackle as a team with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-427",
    text: "Plan a surprise around a tradition to start in person if you can",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-428",
    text: "Plan a surprise around a book or article that made you think of them as a mid-day surprise",
    category: "This Week",
    timeEstimate: "8 min",
  },
  {
    id: "dare-429",
    text: "Plan a surprise around what you are rooting for them on and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-430",
    text: "Plan a surprise around a silly moment you loved and read it aloud if possible",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-431",
    text: "Plan a surprise around their patience with you today",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-432",
    text: "Plan a surprise around a gift idea \"just because\" before bed",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-433",
    text: "Plan a surprise around a hug they gave that you remember when you see them next",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-434",
    text: "Plan a surprise around a goal you want to support this week",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-435",
    text: "Plan a surprise around a fear you want to ease for them without telling them first",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-436",
    text: "Plan a surprise around a moment they made you laugh with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-437",
    text: "Plan a surprise around how they show love in small ways in person if you can",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-438",
    text: "Plan a surprise around a photo scavenger hunt theme as a mid-day surprise",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-439",
    text: "Plan a surprise around a playlist for a road trip and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-440",
    text: "Plan a surprise around a handwritten letter and read it aloud if possible",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-441",
    text: "Plan a surprise around a breakfast surprise today",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-442",
    text: "Plan a surprise around a chore you can take off their plate before bed",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-443",
    text: "Plan a surprise around a cozy night in plan when you see them next",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-444",
    text: "Plan a surprise around a public compliment this week",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-445",
    text: "Plan a surprise around a dance party in the kitchen without telling them first",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-446",
    text: "Plan a surprise around a stargazing moment with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-447",
    text: "Plan a surprise around a walk with no destination in person if you can",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-448",
    text: "Plan a surprise around a favorite photo and its story as a mid-day surprise",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-449",
    text: "Plan a surprise around a 60-second compliment marathon and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-450",
    text: "Plan a surprise around a thank-you for something small and read it aloud if possible",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-451",
    text: "Create a playlist inspired by something you admire about them today",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-452",
    text: "Create a playlist inspired by your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-453",
    text: "Create a playlist inspired by three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-454",
    text: "Create a playlist inspired by a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-455",
    text: "Create a playlist inspired by a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-456",
    text: "Create a playlist inspired by a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-457",
    text: "Create a playlist inspired by a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-458",
    text: "Create a playlist inspired by something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-459",
    text: "Create a playlist inspired by your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-460",
    text: "Create a playlist inspired by a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-461",
    text: "Create a playlist inspired by what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-462",
    text: "Create a playlist inspired by a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-463",
    text: "Create a playlist inspired by a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-464",
    text: "Create a playlist inspired by how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-465",
    text: "Create a playlist inspired by a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "20 min",
  },
  {
    id: "dare-466",
    text: "Create a playlist inspired by something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "25 min",
  },
  {
    id: "dare-467",
    text: "Create a playlist inspired by a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "30 min",
  },
  {
    id: "dare-468",
    text: "Create a playlist inspired by what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "45 min",
  },
  {
    id: "dare-469",
    text: "Create a playlist inspired by a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "60 min",
  },
  {
    id: "dare-470",
    text: "Create a playlist inspired by a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "2 min",
  },
  {
    id: "dare-471",
    text: "Create a playlist inspired by their kindness to others today",
    category: "Right Now",
    timeEstimate: "5 min",
  },
  {
    id: "dare-472",
    text: "Create a playlist inspired by how they handle stress before bed",
    category: "Today",
    timeEstimate: "8 min",
  },
  {
    id: "dare-473",
    text: "Create a playlist inspired by a meal you want to share when you see them next",
    category: "This Week",
    timeEstimate: "10 min",
  },
  {
    id: "dare-474",
    text: "Create a playlist inspired by a place you want to visit together this week",
    category: "Vulnerability",
    timeEstimate: "12 min",
  },
  {
    id: "dare-475",
    text: "Create a playlist inspired by a show you want to watch together without telling them first",
    category: "Fun",
    timeEstimate: "15 min",
  },
  {
    id: "dare-476",
    text: "Create a playlist inspired by a challenge you want to tackle as a team with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "20 min",
  },
  {
    id: "dare-477",
    text: "Create a playlist inspired by a tradition to start in person if you can",
    category: "Today",
    timeEstimate: "25 min",
  },
  {
    id: "dare-478",
    text: "Create a playlist inspired by a book or article that made you think of them as a mid-day surprise",
    category: "This Week",
    timeEstimate: "30 min",
  },
  {
    id: "dare-479",
    text: "Create a playlist inspired by what you are rooting for them on and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "45 min",
  },
  {
    id: "dare-480",
    text: "Create a playlist inspired by a silly moment you loved and read it aloud if possible",
    category: "Fun",
    timeEstimate: "60 min",
  },
  {
    id: "dare-481",
    text: "Create a playlist inspired by their patience with you today",
    category: "Right Now",
    timeEstimate: "2 min",
  },
  {
    id: "dare-482",
    text: "Create a playlist inspired by a gift idea \"just because\" before bed",
    category: "Today",
    timeEstimate: "5 min",
  },
  {
    id: "dare-483",
    text: "Create a playlist inspired by a hug they gave that you remember when you see them next",
    category: "This Week",
    timeEstimate: "8 min",
  },
  {
    id: "dare-484",
    text: "Create a playlist inspired by a goal you want to support this week",
    category: "Vulnerability",
    timeEstimate: "10 min",
  },
  {
    id: "dare-485",
    text: "Create a playlist inspired by a fear you want to ease for them without telling them first",
    category: "Fun",
    timeEstimate: "12 min",
  },
  {
    id: "dare-486",
    text: "Create a playlist inspired by a moment they made you laugh with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "15 min",
  },
  {
    id: "dare-487",
    text: "Create a playlist inspired by how they show love in small ways in person if you can",
    category: "Today",
    timeEstimate: "20 min",
  },
  {
    id: "dare-488",
    text: "Create a playlist inspired by a photo scavenger hunt theme as a mid-day surprise",
    category: "This Week",
    timeEstimate: "25 min",
  },
  {
    id: "dare-489",
    text: "Create a playlist inspired by a playlist for a road trip and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "30 min",
  },
  {
    id: "dare-490",
    text: "Create a playlist inspired by a handwritten letter and read it aloud if possible",
    category: "Fun",
    timeEstimate: "45 min",
  },
  {
    id: "dare-491",
    text: "Create a playlist inspired by a breakfast surprise today",
    category: "Right Now",
    timeEstimate: "60 min",
  },
  {
    id: "dare-492",
    text: "Create a playlist inspired by a chore you can take off their plate before bed",
    category: "Today",
    timeEstimate: "2 min",
  },
  {
    id: "dare-493",
    text: "Create a playlist inspired by a cozy night in plan when you see them next",
    category: "This Week",
    timeEstimate: "5 min",
  },
  {
    id: "dare-494",
    text: "Create a playlist inspired by a public compliment this week",
    category: "Vulnerability",
    timeEstimate: "8 min",
  },
  {
    id: "dare-495",
    text: "Create a playlist inspired by a dance party in the kitchen without telling them first",
    category: "Fun",
    timeEstimate: "10 min",
  },
  {
    id: "dare-496",
    text: "Create a playlist inspired by a stargazing moment with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "12 min",
  },
  {
    id: "dare-497",
    text: "Create a playlist inspired by a walk with no destination in person if you can",
    category: "Today",
    timeEstimate: "15 min",
  },
  {
    id: "dare-498",
    text: "Create a playlist inspired by a favorite photo and its story as a mid-day surprise",
    category: "This Week",
    timeEstimate: "20 min",
  },
  {
    id: "dare-499",
    text: "Create a playlist inspired by a 60-second compliment marathon and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "25 min",
  },
  {
    id: "dare-500",
    text: "Create a playlist inspired by a thank-you for something small and read it aloud if possible",
    category: "Fun",
    timeEstimate: "30 min",
  },
  {
    id: "dare-501",
    text: "Record a short video about something you admire about them today",
    category: "Right Now",
    timeEstimate: "45 min",
  },
  {
    id: "dare-502",
    text: "Record a short video about your favorite memory this month before bed",
    category: "Today",
    timeEstimate: "60 min",
  },
  {
    id: "dare-503",
    text: "Record a short video about three things you are grateful for when you see them next",
    category: "This Week",
    timeEstimate: "2 min",
  },
  {
    id: "dare-504",
    text: "Record a short video about a dream for your future together this week",
    category: "Vulnerability",
    timeEstimate: "5 min",
  },
  {
    id: "dare-505",
    text: "Record a short video about a song that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "8 min",
  },
  {
    id: "dare-506",
    text: "Record a short video about a compliment you have been holding back with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "10 min",
  },
  {
    id: "dare-507",
    text: "Record a short video about a moment you felt proud of them in person if you can",
    category: "Today",
    timeEstimate: "12 min",
  },
  {
    id: "dare-508",
    text: "Record a short video about something they do that makes you feel safe as a mid-day surprise",
    category: "This Week",
    timeEstimate: "15 min",
  },
  {
    id: "dare-509",
    text: "Record a short video about your favorite inside joke and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "20 min",
  },
  {
    id: "dare-510",
    text: "Record a short video about a small thing they did that mattered and read it aloud if possible",
    category: "Fun",
    timeEstimate: "25 min",
  },
  {
    id: "dare-511",
    text: "Record a short video about what you love about their laugh today",
    category: "Right Now",
    timeEstimate: "30 min",
  },
  {
    id: "dare-512",
    text: "Record a short video about a date idea you want to try before bed",
    category: "Today",
    timeEstimate: "45 min",
  },
  {
    id: "dare-513",
    text: "Record a short video about a quality that still surprises you when you see them next",
    category: "This Week",
    timeEstimate: "60 min",
  },
  {
    id: "dare-514",
    text: "Record a short video about how they made your week better this week",
    category: "Vulnerability",
    timeEstimate: "2 min",
  },
  {
    id: "dare-515",
    text: "Record a short video about a photo that reminds you of them without telling them first",
    category: "Fun",
    timeEstimate: "5 min",
  },
  {
    id: "dare-516",
    text: "Record a short video about something you want to do together soon with a specific detail from this week",
    category: "Right Now",
    timeEstimate: "8 min",
  },
  {
    id: "dare-517",
    text: "Record a short video about a habit of theirs you secretly love in person if you can",
    category: "Today",
    timeEstimate: "10 min",
  },
  {
    id: "dare-518",
    text: "Record a short video about what you miss when apart as a mid-day surprise",
    category: "This Week",
    timeEstimate: "12 min",
  },
  {
    id: "dare-519",
    text: "Record a short video about a promise you want to make them and follow up with a hug",
    category: "Vulnerability",
    timeEstimate: "15 min",
  },
  {
    id: "dare-520",
    text: "Record a short video about a story from when you first met and read it aloud if possible",
    category: "Fun",
    timeEstimate: "20 min",
  },
];
