// 32 dares — ~1 month before the same dare returns.
export const DARE_CATALOG = [
  {
    id: 'voice-note',
    text: 'Send your partner a voice note saying three things you love about them',
    category: 'Right Now',
    timeEstimate: '5 min',
  },
  {
    id: 'surprise-15',
    text: 'Plan a 15-minute surprise for your partner today',
    category: 'Today',
    timeEstimate: '15 min',
  },
  {
    id: 'hidden-note',
    text: 'Write a handwritten note and hide it somewhere they\'ll find it',
    category: 'This Week',
    timeEstimate: '10 min',
  },
  {
    id: 'love-song',
    text: 'Pick a song that describes your partner and share why',
    category: 'Vulnerability',
    timeEstimate: '8 min',
  },
  {
    id: 'compliment-marathon',
    text: 'Give your partner a 60-second compliment marathon',
    category: 'Fun',
    timeEstimate: '2 min',
  },
  {
    id: 'coffee-run',
    text: 'Pick up their favorite drink and leave it with a sweet note',
    category: 'Today',
    timeEstimate: '20 min',
  },
  {
    id: 'memory-text',
    text: 'Text them your favorite memory together and why it still matters',
    category: 'Vulnerability',
    timeEstimate: '5 min',
  },
  {
    id: 'dance-kitchen',
    text: 'Start a two-song kitchen dance party when you see them next',
    category: 'Fun',
    timeEstimate: '10 min',
  },
  {
    id: 'breakfast-bed',
    text: 'Make or order their favorite breakfast and surprise them with it',
    category: 'Today',
    timeEstimate: '25 min',
  },
  {
    id: 'photo-scavenger',
    text: 'Send them 3 photos that remind you of them throughout the day',
    category: 'Fun',
    timeEstimate: '10 min',
  },
  {
    id: 'gratitude-list',
    text: 'Write a list of 10 things you\'re grateful for about your partner',
    category: 'Vulnerability',
    timeEstimate: '8 min',
  },
  {
    id: 'no-phone-hour',
    text: 'Spend one hour together with phones put away — just talk or cuddle',
    category: 'Right Now',
    timeEstimate: '60 min',
  },
  {
    id: 'playlist-gift',
    text: 'Create a 5-song playlist just for them and share it',
    category: 'Today',
    timeEstimate: '15 min',
  },
  {
    id: 'errand-help',
    text: 'Take one thing off their to-do list without being asked',
    category: 'This Week',
    timeEstimate: '30 min',
  },
  {
    id: 'love-letter',
    text: 'Write a short love letter and read it aloud to them',
    category: 'Vulnerability',
    timeEstimate: '12 min',
  },
  {
    id: 'silly-video',
    text: 'Record a silly 15-second video telling them why they\'re amazing',
    category: 'Fun',
    timeEstimate: '5 min',
  },
  {
    id: 'favorite-snack',
    text: 'Stock up on their favorite snack and leave it where they\'ll find it',
    category: 'Today',
    timeEstimate: '15 min',
  },
  {
    id: 'walk-talk',
    text: 'Suggest a 20-minute walk together with no destination',
    category: 'Right Now',
    timeEstimate: '20 min',
  },
  {
    id: 'old-photo',
    text: 'Share your favorite photo of the two of you and the story behind it',
    category: 'Vulnerability',
    timeEstimate: '5 min',
  },
  {
    id: 'massage-offer',
    text: 'Offer a 10-minute shoulder or back massage — no strings attached',
    category: 'Fun',
    timeEstimate: '10 min',
  },
  {
    id: 'date-plan',
    text: 'Plan a full date night for this week and tell them the surprise details',
    category: 'This Week',
    timeEstimate: '20 min',
  },
  {
    id: 'public-compliment',
    text: 'Compliment them in front of a friend or family member today',
    category: 'Vulnerability',
    timeEstimate: '2 min',
  },
  {
    id: 'cook-together',
    text: 'Pick a recipe and cook one meal together tonight',
    category: 'Today',
    timeEstimate: '45 min',
  },
  {
    id: 'inside-joke',
    text: 'Recreate an inside joke or memory in a funny way and send it to them',
    category: 'Fun',
    timeEstimate: '8 min',
  },
  {
    id: 'future-dream',
    text: 'Tell them one specific dream you have for your future together',
    category: 'Vulnerability',
    timeEstimate: '5 min',
  },
  {
    id: 'chore-swap',
    text: 'Do one of their usual chores today without mentioning it first',
    category: 'This Week',
    timeEstimate: '20 min',
  },
  {
    id: 'stargaze',
    text: 'Step outside tonight and look at the sky together for 10 minutes',
    category: 'Right Now',
    timeEstimate: '10 min',
  },
  {
    id: 'favorite-thing',
    text: 'Ask them about their day, then share your favorite moment from it',
    category: 'Fun',
    timeEstimate: '5 min',
  },
  {
    id: 'apology-promise',
    text: 'If something\'s been unresolved, apologize sincerely and name one change you\'ll make',
    category: 'Vulnerability',
    timeEstimate: '10 min',
  },
  {
    id: 'surprise-call',
    text: 'Call them just to say hi — no agenda, no asking for anything',
    category: 'Right Now',
    timeEstimate: '5 min',
  },
  {
    id: 'book-recommend',
    text: 'Recommend something (book, show, article) that made you think of them',
    category: 'Today',
    timeEstimate: '5 min',
  },
  {
    id: 'adventure-plan',
    text: 'Research one new place to explore together and pitch it to them',
    category: 'This Week',
    timeEstimate: '15 min',
  },
];
