// 520 voice bomb prompts — ~74 weeks of unique daily prompts.
export const VOICE_BOMB_PROMPTS = [
  "Tell them something you've never said out loud",
  "Say why you are proud of them today",
  "Share a memory that still makes you smile",
  "Tell them what you noticed about them lately",
  "Say the thing you have been meaning to say",
  "Describe the moment you knew they were yours",
  "Tell them what you love most about their voice",
  "Share one thing they do that melts you",
  "Tell them what you are grateful for this week",
  "Describe your favorite ordinary moment together",
  "Say what you are looking forward to with them",
  "Tell them how they made your day better",
  "Share a compliment you have been holding back",
  "Say what you admire about how they love you",
  "Tell them one thing that made you fall harder",
  "Describe how you feel when you see their name pop up",
  "Share a dream you want to build together",
  "Tell them what you would do on a perfect day with them",
  "Say thank you for something small they did",
  "Tell them what you miss when you are apart",
  "Share what you are excited to tell them in person",
  "Say what makes your relationship uniquely yours",
  "Tell them a secret wish for your future together",
  "Describe the last time they made you laugh",
  "Tell them something you have never said out loud",
  "Tell them something you have never said out loud — start with their name",
  "Say why you are proud of them today — include one tiny detail",
  "Share a memory that still makes you smile — say it like a secret",
  "Tell them what you noticed about them lately — make it playful",
  "Say the thing you have been meaning to say — make it tender",
  "Describe the moment you knew they were yours — end with I love you if it feels true",
  "Tell them what you love most about their voice — be specific",
  "Share one thing they do that melts you — keep it raw and honest",
  "Tell them what you are grateful for this week — no filter",
  "Describe your favorite ordinary moment together — like they are right here",
  "Say what you are looking forward to with them — start with their name",
  "Tell them how they made your day better — include one tiny detail",
  "Share a compliment you have been holding back — say it like a secret",
  "Say what you admire about how they love you — make it playful",
  "Tell them one thing that made you fall harder — make it tender",
  "Describe how you feel when you see their name pop up — end with I love you if it feels true",
  "Share a dream you want to build together — be specific",
  "Tell them what you would do on a perfect day with them — keep it raw and honest",
  "Say thank you for something small they did — no filter",
  "Tell them what you miss when you are apart — like they are right here",
  "Share what you are excited to tell them in person — start with their name",
  "Say what makes your relationship uniquely yours — include one tiny detail",
  "Tell them a secret wish for your future together — say it like a secret",
  "Describe the last time they made you laugh — make it playful",
  "Tell them what you love about their laugh",
  "Tell them what you love about their laugh — make it tender",
  "Say what you want them to know before sleep tonight",
  "Say what you want them to know before sleep tonight — end with I love you if it feels true",
  "Share a moment you felt lucky to be with them",
  "Share a moment you felt lucky to be with them — be specific",
  "Tell them one thing that still gives you butterflies",
  "Tell them one thing that still gives you butterflies — keep it raw and honest",
  "Describe how they calm you down",
  "Describe how they calm you down — no filter",
  "Say what you appreciate about their patience",
  "Say what you appreciate about their patience — like they are right here",
  "Tell them a story from when you first met",
  "Tell them a story from when you first met — start with their name",
  "Share what you are proud of us for",
  "Share what you are proud of us for — include one tiny detail",
  "Say what you hope they never forget about you",
  "Say what you hope they never forget about you — say it like a secret",
  "Tell them what song reminds you of them and why",
  "Tell them what song reminds you of them and why — make it playful",
  "Describe your favorite hug from them",
  "Describe your favorite hug from them — make it tender",
  "Say what you are excited about this month",
  "Say what you are excited about this month — end with I love you if it feels true",
  "Tell them one way they inspire you",
  "Tell them one way they inspire you — be specific",
  "Share what you love about lazy days together",
  "Share what you love about lazy days together — keep it raw and honest",
  "Say what you would tell them if you had 30 seconds",
  "Say what you would tell them if you had 30 seconds — no filter",
  "Tell them what you are rooting for them on",
  "Tell them what you are rooting for them on — like they are right here",
  "Tell them something you have never said out loud — keep it raw and honest",
  "Say why you are proud of them today — no filter",
  "Share a memory that still makes you smile — like they are right here",
  "Tell them what you noticed about them lately — start with their name",
  "Say the thing you have been meaning to say — include one tiny detail",
  "Describe the moment you knew they were yours — say it like a secret",
  "Tell them what you love most about their voice — make it playful",
  "Share one thing they do that melts you — make it tender",
  "Tell them what you are grateful for this week — end with I love you if it feels true",
  "Describe your favorite ordinary moment together — be specific",
  "Say what you are looking forward to with them — keep it raw and honest",
  "Tell them how they made your day better — no filter",
  "Share a compliment you have been holding back — like they are right here",
  "Say what you admire about how they love you — start with their name",
  "Tell them one thing that made you fall harder — include one tiny detail",
  "Describe how you feel when you see their name pop up — say it like a secret",
  "Share a dream you want to build together — make it playful",
  "Tell them what you would do on a perfect day with them — make it tender",
  "Say thank you for something small they did — end with I love you if it feels true",
  "Tell them what you miss when you are apart — be specific",
  "Share what you are excited to tell them in person — keep it raw and honest",
  "Say what makes your relationship uniquely yours — no filter",
  "Tell them a secret wish for your future together — like they are right here",
  "Describe the last time they made you laugh — start with their name",
  "Tell them what you love about their laugh — include one tiny detail",
  "Say what you want them to know before sleep tonight — say it like a secret",
  "Share a moment you felt lucky to be with them — make it playful",
  "Tell them one thing that still gives you butterflies — make it tender",
  "Describe how they calm you down — end with I love you if it feels true",
  "Say what you appreciate about their patience — be specific",
  "Tell them a story from when you first met — keep it raw and honest",
  "Share what you are proud of us for — no filter",
  "Say what you hope they never forget about you — like they are right here",
  "Tell them what song reminds you of them and why — start with their name",
  "Describe your favorite hug from them — include one tiny detail",
  "Say what you are excited about this month — say it like a secret",
  "Tell them one way they inspire you — make it playful",
  "Share what you love about lazy days together — make it tender",
  "Say what you would tell them if you had 30 seconds — end with I love you if it feels true",
  "Tell them what you are rooting for them on — be specific",
  "Tell them something you have never said out loud — be specific",
  "Tell them something you have never said out loud — keep it honest",
  "Tell them something you have never said out loud — no filter",
  "Tell them something you have never said out loud — like they are right here",
  "Tell them something you have never said out loud — include one tiny detail",
  "Tell them something you have never said out loud — say it like a secret",
  "Tell them something you have never said out loud — make it playful",
  "Tell them something you have never said out loud — make it tender",
  "Tell them something you have never said out loud — end with I love you if it feels true",
  "Tell them something you have never said out loud — keep it under 30 seconds",
  "Tell them something you have never said out loud — say it slowly",
  "Tell them something you have never said out loud — smile while you say it",
  "Tell them why you are proud of them today",
  "Tell them why you are proud of them today — be specific",
  "Tell them why you are proud of them today — keep it honest",
  "Tell them why you are proud of them today — no filter",
  "Tell them why you are proud of them today — like they are right here",
  "Tell them why you are proud of them today — start with their name",
  "Tell them why you are proud of them today — include one tiny detail",
  "Tell them why you are proud of them today — say it like a secret",
  "Tell them why you are proud of them today — make it playful",
  "Tell them why you are proud of them today — make it tender",
  "Tell them why you are proud of them today — end with I love you if it feels true",
  "Tell them why you are proud of them today — keep it under 30 seconds",
  "Tell them why you are proud of them today — say it slowly",
  "Tell them why you are proud of them today — smile while you say it",
  "Tell them a memory that still makes you smile",
  "Tell them a memory that still makes you smile — be specific",
  "Tell them a memory that still makes you smile — keep it honest",
  "Tell them a memory that still makes you smile — no filter",
  "Tell them a memory that still makes you smile — like they are right here",
  "Tell them a memory that still makes you smile — start with their name",
  "Tell them a memory that still makes you smile — include one tiny detail",
  "Tell them a memory that still makes you smile — say it like a secret",
  "Tell them a memory that still makes you smile — make it playful",
  "Tell them a memory that still makes you smile — make it tender",
  "Tell them a memory that still makes you smile — end with I love you if it feels true",
  "Tell them a memory that still makes you smile — keep it under 30 seconds",
  "Tell them a memory that still makes you smile — say it slowly",
  "Tell them a memory that still makes you smile — smile while you say it",
  "Tell them what you noticed about them lately — be specific",
  "Tell them what you noticed about them lately — keep it honest",
  "Tell them what you noticed about them lately — no filter",
  "Tell them what you noticed about them lately — like they are right here",
  "Tell them what you noticed about them lately — include one tiny detail",
  "Tell them what you noticed about them lately — say it like a secret",
  "Tell them what you noticed about them lately — make it tender",
  "Tell them what you noticed about them lately — end with I love you if it feels true",
  "Tell them what you noticed about them lately — keep it under 30 seconds",
  "Tell them what you noticed about them lately — say it slowly",
  "Tell them what you noticed about them lately — smile while you say it",
  "Tell them the thing you have been meaning to say",
  "Tell them the thing you have been meaning to say — be specific",
  "Tell them the thing you have been meaning to say — keep it honest",
  "Tell them the thing you have been meaning to say — no filter",
  "Tell them the thing you have been meaning to say — like they are right here",
  "Tell them the thing you have been meaning to say — start with their name",
  "Tell them the thing you have been meaning to say — include one tiny detail",
  "Tell them the thing you have been meaning to say — say it like a secret",
  "Tell them the thing you have been meaning to say — make it playful",
  "Tell them the thing you have been meaning to say — make it tender",
  "Tell them the thing you have been meaning to say — end with I love you if it feels true",
  "Tell them the thing you have been meaning to say — keep it under 30 seconds",
  "Tell them the thing you have been meaning to say — say it slowly",
  "Tell them the thing you have been meaning to say — smile while you say it",
  "Tell them the moment you knew they were yours",
  "Tell them the moment you knew they were yours — be specific",
  "Tell them the moment you knew they were yours — keep it honest",
  "Tell them the moment you knew they were yours — no filter",
  "Tell them the moment you knew they were yours — like they are right here",
  "Tell them the moment you knew they were yours — start with their name",
  "Tell them the moment you knew they were yours — include one tiny detail",
  "Tell them the moment you knew they were yours — say it like a secret",
  "Tell them the moment you knew they were yours — make it playful",
  "Tell them the moment you knew they were yours — make it tender",
  "Tell them the moment you knew they were yours — end with I love you if it feels true",
  "Tell them the moment you knew they were yours — keep it under 30 seconds",
  "Tell them the moment you knew they were yours — say it slowly",
  "Tell them the moment you knew they were yours — smile while you say it",
  "Tell them what you love most about their voice — keep it honest",
  "Tell them what you love most about their voice — no filter",
  "Tell them what you love most about their voice — like they are right here",
  "Tell them what you love most about their voice — start with their name",
  "Tell them what you love most about their voice — include one tiny detail",
  "Tell them what you love most about their voice — say it like a secret",
  "Tell them what you love most about their voice — make it tender",
  "Tell them what you love most about their voice — end with I love you if it feels true",
  "Tell them what you love most about their voice — keep it under 30 seconds",
  "Tell them what you love most about their voice — say it slowly",
  "Tell them what you love most about their voice — smile while you say it",
  "Tell them one thing they do that melts you",
  "Tell them one thing they do that melts you — be specific",
  "Tell them one thing they do that melts you — keep it honest",
  "Tell them one thing they do that melts you — no filter",
  "Tell them one thing they do that melts you — like they are right here",
  "Tell them one thing they do that melts you — start with their name",
  "Tell them one thing they do that melts you — include one tiny detail",
  "Tell them one thing they do that melts you — say it like a secret",
  "Tell them one thing they do that melts you — make it playful",
  "Tell them one thing they do that melts you — make it tender",
  "Tell them one thing they do that melts you — end with I love you if it feels true",
  "Tell them one thing they do that melts you — keep it under 30 seconds",
  "Tell them one thing they do that melts you — say it slowly",
  "Tell them one thing they do that melts you — smile while you say it",
  "Tell them what you are grateful for this week — be specific",
  "Tell them what you are grateful for this week — keep it honest",
  "Tell them what you are grateful for this week — like they are right here",
  "Tell them what you are grateful for this week — start with their name",
  "Tell them what you are grateful for this week — include one tiny detail",
  "Tell them what you are grateful for this week — say it like a secret",
  "Tell them what you are grateful for this week — make it playful",
  "Tell them what you are grateful for this week — make it tender",
  "Tell them what you are grateful for this week — keep it under 30 seconds",
  "Tell them what you are grateful for this week — say it slowly",
  "Tell them what you are grateful for this week — smile while you say it",
  "Tell them your favorite ordinary moment together",
  "Tell them your favorite ordinary moment together — be specific",
  "Tell them your favorite ordinary moment together — keep it honest",
  "Tell them your favorite ordinary moment together — no filter",
  "Tell them your favorite ordinary moment together — like they are right here",
  "Tell them your favorite ordinary moment together — start with their name",
  "Tell them your favorite ordinary moment together — include one tiny detail",
  "Tell them your favorite ordinary moment together — say it like a secret",
  "Tell them your favorite ordinary moment together — make it playful",
  "Tell them your favorite ordinary moment together — make it tender",
  "Tell them your favorite ordinary moment together — end with I love you if it feels true",
  "Tell them your favorite ordinary moment together — keep it under 30 seconds",
  "Tell them your favorite ordinary moment together — say it slowly",
  "Tell them your favorite ordinary moment together — smile while you say it",
  "Tell them what you are looking forward to with them",
  "Tell them what you are looking forward to with them — be specific",
  "Tell them what you are looking forward to with them — keep it honest",
  "Tell them what you are looking forward to with them — no filter",
  "Tell them what you are looking forward to with them — like they are right here",
  "Tell them what you are looking forward to with them — start with their name",
  "Tell them what you are looking forward to with them — include one tiny detail",
  "Tell them what you are looking forward to with them — say it like a secret",
  "Tell them what you are looking forward to with them — make it playful",
  "Tell them what you are looking forward to with them — make it tender",
  "Tell them what you are looking forward to with them — end with I love you if it feels true",
  "Tell them what you are looking forward to with them — keep it under 30 seconds",
  "Tell them what you are looking forward to with them — say it slowly",
  "Tell them what you are looking forward to with them — smile while you say it",
  "Tell them how they made your day better — be specific",
  "Tell them how they made your day better — keep it honest",
  "Tell them how they made your day better — like they are right here",
  "Tell them how they made your day better — start with their name",
  "Tell them how they made your day better — say it like a secret",
  "Tell them how they made your day better — make it playful",
  "Tell them how they made your day better — make it tender",
  "Tell them how they made your day better — end with I love you if it feels true",
  "Tell them how they made your day better — keep it under 30 seconds",
  "Tell them how they made your day better — say it slowly",
  "Tell them how they made your day better — smile while you say it",
  "Tell them a compliment you have been holding back",
  "Tell them a compliment you have been holding back — be specific",
  "Tell them a compliment you have been holding back — keep it honest",
  "Tell them a compliment you have been holding back — no filter",
  "Tell them a compliment you have been holding back — like they are right here",
  "Tell them a compliment you have been holding back — start with their name",
  "Tell them a compliment you have been holding back — include one tiny detail",
  "Tell them a compliment you have been holding back — say it like a secret",
  "Tell them a compliment you have been holding back — make it playful",
  "Tell them a compliment you have been holding back — make it tender",
  "Tell them a compliment you have been holding back — end with I love you if it feels true",
  "Tell them a compliment you have been holding back — keep it under 30 seconds",
  "Tell them a compliment you have been holding back — say it slowly",
  "Tell them a compliment you have been holding back — smile while you say it",
  "Tell them what you admire about how they love you",
  "Tell them what you admire about how they love you — be specific",
  "Tell them what you admire about how they love you — keep it honest",
  "Tell them what you admire about how they love you — no filter",
  "Tell them what you admire about how they love you — like they are right here",
  "Tell them what you admire about how they love you — start with their name",
  "Tell them what you admire about how they love you — include one tiny detail",
  "Tell them what you admire about how they love you — say it like a secret",
  "Tell them what you admire about how they love you — make it playful",
  "Tell them what you admire about how they love you — make it tender",
  "Tell them what you admire about how they love you — end with I love you if it feels true",
  "Tell them what you admire about how they love you — keep it under 30 seconds",
  "Tell them what you admire about how they love you — say it slowly",
  "Tell them what you admire about how they love you — smile while you say it",
  "Tell them one thing that made you fall harder — be specific",
  "Tell them one thing that made you fall harder — keep it honest",
  "Tell them one thing that made you fall harder — no filter",
  "Tell them one thing that made you fall harder — like they are right here",
  "Tell them one thing that made you fall harder — start with their name",
  "Tell them one thing that made you fall harder — say it like a secret",
  "Tell them one thing that made you fall harder — make it playful",
  "Tell them one thing that made you fall harder — end with I love you if it feels true",
  "Tell them one thing that made you fall harder — keep it under 30 seconds",
  "Tell them one thing that made you fall harder — say it slowly",
  "Tell them one thing that made you fall harder — smile while you say it",
  "Tell them how you feel when you see their name pop up",
  "Tell them how you feel when you see their name pop up — be specific",
  "Tell them how you feel when you see their name pop up — keep it honest",
  "Tell them how you feel when you see their name pop up — no filter",
  "Tell them how you feel when you see their name pop up — like they are right here",
  "Tell them how you feel when you see their name pop up — start with their name",
  "Tell them how you feel when you see their name pop up — include one tiny detail",
  "Tell them how you feel when you see their name pop up — say it like a secret",
  "Tell them how you feel when you see their name pop up — make it playful",
  "Tell them how you feel when you see their name pop up — make it tender",
  "Tell them how you feel when you see their name pop up — end with I love you if it feels true",
  "Tell them how you feel when you see their name pop up — keep it under 30 seconds",
  "Tell them how you feel when you see their name pop up — say it slowly",
  "Tell them how you feel when you see their name pop up — smile while you say it",
  "Tell them a dream you want to build together",
  "Tell them a dream you want to build together — be specific",
  "Tell them a dream you want to build together — keep it honest",
  "Tell them a dream you want to build together — no filter",
  "Tell them a dream you want to build together — like they are right here",
  "Tell them a dream you want to build together — start with their name",
  "Tell them a dream you want to build together — include one tiny detail",
  "Tell them a dream you want to build together — say it like a secret",
  "Tell them a dream you want to build together — make it playful",
  "Tell them a dream you want to build together — make it tender",
  "Tell them a dream you want to build together — end with I love you if it feels true",
  "Tell them a dream you want to build together — keep it under 30 seconds",
  "Tell them a dream you want to build together — say it slowly",
  "Tell them a dream you want to build together — smile while you say it",
  "Tell them what you would do on a perfect day with them — be specific",
  "Tell them what you would do on a perfect day with them — keep it honest",
  "Tell them what you would do on a perfect day with them — no filter",
  "Tell them what you would do on a perfect day with them — like they are right here",
  "Tell them what you would do on a perfect day with them — start with their name",
  "Tell them what you would do on a perfect day with them — include one tiny detail",
  "Tell them what you would do on a perfect day with them — say it like a secret",
  "Tell them what you would do on a perfect day with them — make it playful",
  "Tell them what you would do on a perfect day with them — end with I love you if it feels true",
  "Tell them what you would do on a perfect day with them — keep it under 30 seconds",
  "Tell them what you would do on a perfect day with them — say it slowly",
  "Tell them what you would do on a perfect day with them — smile while you say it",
  "Tell them thank you for something small they did",
  "Tell them thank you for something small they did — be specific",
  "Tell them thank you for something small they did — keep it honest",
  "Tell them thank you for something small they did — no filter",
  "Tell them thank you for something small they did — like they are right here",
  "Tell them thank you for something small they did — start with their name",
  "Tell them thank you for something small they did — include one tiny detail",
  "Tell them thank you for something small they did — say it like a secret",
  "Tell them thank you for something small they did — make it playful",
  "Tell them thank you for something small they did — make it tender",
  "Tell them thank you for something small they did — end with I love you if it feels true",
  "Tell them thank you for something small they did — keep it under 30 seconds",
  "Tell them thank you for something small they did — say it slowly",
  "Tell them thank you for something small they did — smile while you say it",
  "Tell them what you miss when you are apart — keep it honest",
  "Tell them what you miss when you are apart — no filter",
  "Tell them what you miss when you are apart — start with their name",
  "Tell them what you miss when you are apart — include one tiny detail",
  "Tell them what you miss when you are apart — say it like a secret",
  "Tell them what you miss when you are apart — make it playful",
  "Tell them what you miss when you are apart — make it tender",
  "Tell them what you miss when you are apart — end with I love you if it feels true",
  "Tell them what you miss when you are apart — keep it under 30 seconds",
  "Tell them what you miss when you are apart — say it slowly",
  "Tell them what you miss when you are apart — smile while you say it",
  "Tell them what you are excited to tell them in person",
  "Tell them what you are excited to tell them in person — be specific",
  "Tell them what you are excited to tell them in person — keep it honest",
  "Tell them what you are excited to tell them in person — no filter",
  "Tell them what you are excited to tell them in person — like they are right here",
  "Tell them what you are excited to tell them in person — start with their name",
  "Tell them what you are excited to tell them in person — include one tiny detail",
  "Tell them what you are excited to tell them in person — say it like a secret",
  "Tell them what you are excited to tell them in person — make it playful",
  "Tell them what you are excited to tell them in person — make it tender",
  "Tell them what you are excited to tell them in person — end with I love you if it feels true",
  "Tell them what you are excited to tell them in person — keep it under 30 seconds",
  "Tell them what you are excited to tell them in person — say it slowly",
  "Tell them what you are excited to tell them in person — smile while you say it",
  "Tell them what makes your relationship uniquely yours",
  "Tell them what makes your relationship uniquely yours — be specific",
  "Tell them what makes your relationship uniquely yours — keep it honest",
  "Tell them what makes your relationship uniquely yours — no filter",
  "Tell them what makes your relationship uniquely yours — like they are right here",
  "Tell them what makes your relationship uniquely yours — start with their name",
  "Tell them what makes your relationship uniquely yours — include one tiny detail",
  "Tell them what makes your relationship uniquely yours — say it like a secret",
  "Tell them what makes your relationship uniquely yours — make it playful",
  "Tell them what makes your relationship uniquely yours — make it tender",
  "Tell them what makes your relationship uniquely yours — end with I love you if it feels true",
  "Tell them what makes your relationship uniquely yours — keep it under 30 seconds",
  "Tell them what makes your relationship uniquely yours — say it slowly",
  "Tell them what makes your relationship uniquely yours — smile while you say it",
  "Tell them a secret wish for your future together — be specific",
  "Tell them a secret wish for your future together — keep it honest",
  "Tell them a secret wish for your future together — no filter",
  "Tell them a secret wish for your future together — start with their name",
  "Tell them a secret wish for your future together — include one tiny detail",
  "Tell them a secret wish for your future together — make it playful",
  "Tell them a secret wish for your future together — make it tender",
  "Tell them a secret wish for your future together — end with I love you if it feels true",
  "Tell them a secret wish for your future together — keep it under 30 seconds",
  "Tell them a secret wish for your future together — say it slowly",
  "Tell them a secret wish for your future together — smile while you say it",
  "Tell them the last time they made you laugh",
  "Tell them the last time they made you laugh — be specific",
  "Tell them the last time they made you laugh — keep it honest",
  "Tell them the last time they made you laugh — no filter",
  "Tell them the last time they made you laugh — like they are right here",
  "Tell them the last time they made you laugh — start with their name",
  "Tell them the last time they made you laugh — include one tiny detail",
  "Tell them the last time they made you laugh — say it like a secret",
  "Tell them the last time they made you laugh — make it playful",
  "Tell them the last time they made you laugh — make it tender",
  "Tell them the last time they made you laugh — end with I love you if it feels true",
  "Tell them the last time they made you laugh — keep it under 30 seconds",
  "Tell them the last time they made you laugh — say it slowly",
  "Tell them the last time they made you laugh — smile while you say it",
  "Tell them what you love about their laugh — be specific",
  "Tell them what you love about their laugh — keep it honest",
  "Tell them what you love about their laugh — no filter",
  "Tell them what you love about their laugh — like they are right here",
  "Tell them what you love about their laugh — start with their name",
  "Tell them what you love about their laugh — say it like a secret",
  "Tell them what you love about their laugh — make it playful",
  "Tell them what you love about their laugh — end with I love you if it feels true",
  "Tell them what you love about their laugh — keep it under 30 seconds",
  "Tell them what you love about their laugh — say it slowly",
  "Tell them what you love about their laugh — smile while you say it",
  "Tell them what you want them to know before sleep",
  "Tell them what you want them to know before sleep — be specific",
  "Tell them what you want them to know before sleep — keep it honest",
  "Tell them what you want them to know before sleep — no filter",
  "Tell them what you want them to know before sleep — like they are right here",
  "Tell them what you want them to know before sleep — start with their name",
  "Tell them what you want them to know before sleep — include one tiny detail",
  "Tell them what you want them to know before sleep — say it like a secret",
  "Tell them what you want them to know before sleep — make it playful",
  "Tell them what you want them to know before sleep — make it tender",
  "Tell them what you want them to know before sleep — end with I love you if it feels true",
  "Tell them what you want them to know before sleep — keep it under 30 seconds",
  "Tell them what you want them to know before sleep — say it slowly",
  "Tell them what you want them to know before sleep — smile while you say it",
  "Tell them a moment you felt lucky to be with them",
  "Tell them a moment you felt lucky to be with them — be specific",
  "Tell them a moment you felt lucky to be with them — keep it honest",
  "Tell them a moment you felt lucky to be with them — no filter",
  "Tell them a moment you felt lucky to be with them — like they are right here",
  "Tell them a moment you felt lucky to be with them — start with their name",
  "Tell them a moment you felt lucky to be with them — include one tiny detail",
  "Tell them a moment you felt lucky to be with them — say it like a secret",
  "Tell them a moment you felt lucky to be with them — make it playful",
  "Tell them a moment you felt lucky to be with them — make it tender",
  "Tell them a moment you felt lucky to be with them — end with I love you if it feels true",
  "Tell them a moment you felt lucky to be with them — keep it under 30 seconds",
  "Tell them a moment you felt lucky to be with them — say it slowly",
  "Tell them a moment you felt lucky to be with them — smile while you say it",
  "Tell them one thing that still gives you butterflies — be specific",
  "Tell them one thing that still gives you butterflies — keep it honest",
  "Tell them one thing that still gives you butterflies — no filter",
  "Tell them one thing that still gives you butterflies — like they are right here",
  "Tell them one thing that still gives you butterflies — start with their name",
  "Tell them one thing that still gives you butterflies — include one tiny detail",
  "Tell them one thing that still gives you butterflies — say it like a secret",
  "Tell them one thing that still gives you butterflies — make it playful",
  "Tell them one thing that still gives you butterflies — end with I love you if it feels true",
  "Tell them one thing that still gives you butterflies — keep it under 30 seconds",
  "Tell them one thing that still gives you butterflies — say it slowly",
  "Tell them one thing that still gives you butterflies — smile while you say it",
  "Tell them how they calm you down",
  "Tell them how they calm you down — be specific",
  "Tell them how they calm you down — keep it honest",
  "Tell them how they calm you down — no filter",
  "Tell them how they calm you down — like they are right here",
  "Tell them how they calm you down — start with their name",
  "Tell them how they calm you down — include one tiny detail",
  "Tell them how they calm you down — say it like a secret",
  "Tell them how they calm you down — make it playful",
  "Tell them how they calm you down — make it tender",
  "Tell them how they calm you down — end with I love you if it feels true",
  "Tell them how they calm you down — keep it under 30 seconds",
  "Tell them how they calm you down — say it slowly",
  "Tell them how they calm you down — smile while you say it",
  "Tell them what you appreciate about their patience",
  "Tell them what you appreciate about their patience — be specific",
  "Tell them what you appreciate about their patience — keep it honest",
  "Tell them what you appreciate about their patience — no filter",
  "Tell them what you appreciate about their patience — like they are right here",
  "Tell them what you appreciate about their patience — start with their name",
  "Tell them what you appreciate about their patience — include one tiny detail",
  "Tell them what you appreciate about their patience — say it like a secret",
  "Tell them what you appreciate about their patience — make it playful",
  "Tell them what you appreciate about their patience — make it tender",
  "Tell them what you appreciate about their patience — end with I love you if it feels true",
  "Tell them what you appreciate about their patience — keep it under 30 seconds",
  "Tell them what you appreciate about their patience — say it slowly",
  "Tell them what you appreciate about their patience — smile while you say it",
  "Tell them a story from when you first met — be specific",
  "Tell them a story from when you first met — keep it honest",
  "Tell them a story from when you first met — no filter",
  "Tell them a story from when you first met — like they are right here",
  "Tell them a story from when you first met — include one tiny detail",
  "Tell them a story from when you first met — say it like a secret",
  "Tell them a story from when you first met — make it playful",
  "Tell them a story from when you first met — make it tender",
  "Tell them a story from when you first met — end with I love you if it feels true",
];
