export const VOICE_BOMB_PROMPTS = [
  "Tell them something you've never said out loud",
  'Say why you are proud of them today',
  'Share a memory that still makes you smile',
  'Tell them what you noticed about them lately',
  'Say the thing you have been meaning to say',
  'Describe the moment you knew they were yours',
  'Tell them what you love most about their voice',
  'Share one thing they do that melts you',
  'Tell them what you are grateful for this week',
  'Describe your favorite ordinary moment together',
  'Say what you are looking forward to with them',
  'Tell them how they made your day better',
  'Share a compliment you have been holding back',
  'Say what you admire about how they love you',
  'Tell them one thing that made you fall harder',
  'Describe how you feel when you see their name pop up',
  'Share a dream you want to build together',
  'Tell them what you would do on a perfect day with them',
  'Say thank you for something small they did',
  'Tell them what you miss when you are apart',
  'Share what you are excited to tell them in person',
  'Say what makes your relationship uniquely yours',
  'Tell them a secret wish for your future together',
  'Describe the last time they made you laugh',
];
