// 100 "Who's more likely" prompts — 20 unique daily batches before the cycle repeats.
export const WHO_MORE_LIKELY = [
  'Who\'s more likely to plan a surprise date?',
  'Who\'s more likely to stay up late binge-watching?',
  'Who\'s more likely to cry during a movie?',
  'Who\'s more likely to forget an anniversary?',
  'Who\'s more likely to start a dance party in the kitchen?',
  'Who\'s more likely to apologize first after a fight?',
  'Who\'s more likely to order dessert for the table?',
  'Who\'s more likely to get lost even with GPS?',
  'Who\'s more likely to send a good morning text?',
  'Who\'s more likely to hog the blankets at night?',
  'Who\'s more likely to suggest a spontaneous road trip?',
  'Who\'s more likely to remember everyone\'s birthday?',
  'Who\'s more likely to burn something while cooking?',
  'Who\'s more likely to fall asleep during a movie?',
  'Who\'s more likely to take forever getting ready?',
  'Who\'s more likely to start singing in public?',
  'Who\'s more likely to win an argument?',
  'Who\'s more likely to be the bigger flirt?',
  'Who\'s more likely to plan the vacation?',
  'Who\'s more likely to spend money on something silly?',
  'Who\'s more likely to get hangry?',
  'Who\'s more likely to befriend a stranger?',
  'Who\'s more likely to send a meme at 2 AM?',
  'Who\'s more likely to cry at a wedding?',
  'Who\'s more likely to be the designated photographer?',
  'Who\'s more likely to suggest staying in over going out?',
  'Who\'s more likely to have a secret snack stash?',
  'Who\'s more likely to be the first one on the dance floor?',
  'Who\'s more likely to forget where they parked?',
  'Who\'s more likely to say "I love you" first?',
  'Who\'s more likely to pick the restaurant?',
  'Who\'s more likely to binge a new show in one weekend?',
  'Who\'s more likely to be the cuddlier one?',
  'Who\'s more likely to get competitive during a game?',
  'Who\'s more likely to leave voice notes instead of texting?',
  'Who\'s more likely to wake up early on a weekend?',
  'Who\'s more likely to be the messy one?',
  'Who\'s more likely to plan a picnic?',
  'Who\'s more likely to talk to pets like they\'re people?',
  'Who\'s more likely to suggest a couple selfie?',
  'Who\'s more likely to double-text when nervous?',
  'Who\'s more likely to cry happy tears?',
  'Who\'s more likely to forget to reply for hours?',
  'Who\'s more likely to plan every detail of a trip?',
  'Who\'s more likely to suggest trying a new restaurant?',
  'Who\'s more likely to fall for a scam email?',
  'Who\'s more likely to be the peacemaker in a group?',
  'Who\'s more likely to have a five-step skincare routine?',
  'Who\'s more likely to laugh at their own jokes?',
  'Who\'s more likely to read the menu before arriving?',
  'Who\'s more likely to suggest a couples workout?',
  'Who\'s more likely to keep every ticket stub and memento?',
  'Who\'s more likely to be the designated driver?',
  'Who\'s more likely to start a deep conversation at midnight?',
  'Who\'s more likely to overshare on social media?',
  'Who\'s more likely to be scared of spiders?',
  'Who\'s more likely to suggest a board game night?',
  'Who\'s more likely to remember what you ordered last time?',
  'Who\'s more likely to be the early bird?',
  'Who\'s more likely to suggest rewatching a comfort show?',
  'Who\'s more likely to buy gifts "just because"?',
  'Who\'s more likely to get sunburned on vacation?',
  'Who\'s more likely to initiate a hug after a long day?',
  'Who\'s more likely to be the better cook?',
  'Who\'s more likely to talk through a problem immediately?',
  'Who\'s more likely to need alone time to recharge?',
  'Who\'s more likely to suggest a fancy date night?',
  'Who\'s more likely to be the bigger foodie?',
  'Who\'s more likely to cry during a commercial?',
  'Who\'s more likely to be the planner for holidays?',
  'Who\'s more likely to suggest a staycation?',
  'Who\'s more likely to win at trivia night?',
  'Who\'s more likely to be the handyman or handywoman?',
  'Who\'s more likely to suggest matching outfits?',
  'Who\'s more likely to be the life of the party?',
  'Who\'s more likely to read relationship advice online?',
  'Who\'s more likely to suggest a digital detox day?',
  'Who\'s more likely to be the sentimental one?',
  'Who\'s more likely to suggest adopting a pet?',
  'Who\'s more likely to be the better gift wrapper?',
  'Who\'s more likely to start a pillow fight?',
  'Who\'s more likely to be the one who says "we need to talk"?',
  'Who\'s more likely to suggest a couples bucket list?',
  'Who\'s more likely to be the bigger procrastinator?',
  'Who\'s more likely to suggest learning a language together?',
  'Who\'s more likely to be the one who fixes things around the house?',
  'Who\'s more likely to suggest a sunrise hike?',
  'Who\'s more likely to be the bigger dreamer?',
  'Who\'s more likely to suggest writing love letters?',
  'Who\'s more likely to be the one who remembers inside jokes?',
  'Who\'s more likely to suggest a cooking class together?',
  'Who\'s more likely to be the more patient one?',
  'Who\'s more likely to suggest a thrift-store date?',
  'Who\'s more likely to be the one who initiates "I\'m sorry"?',
  'Who\'s more likely to suggest stargazing?',
  'Who\'s more likely to be the bigger worrier?',
  'Who\'s more likely to suggest a no-phones dinner?',
  'Who\'s more likely to be the one who plans surprises for friends too?',
  'Who\'s more likely to suggest a couples journal?',
  'Who\'s more likely to be the better dancer?',
  'Who\'s more likely to suggest volunteering together?',
  'Who\'s more likely to be the one who needs the most reassurance?',
  'Who\'s more likely to suggest a random act of kindness for a stranger?',
  'Who\'s more likely to be the bigger romantic?',
  'Who\'s more likely to suggest building something together (furniture, garden, etc.)?',
  'Who\'s more likely to be the one who remembers anniversaries of small moments?',
];
