// 520 prompts with template variants — batches pick ~198 unique stems with variety.
export const WHO_MORE_LIKELY = [
  "Who's more likely to plan a surprise date?",
  "Who's more likely to stay up late binge-watching?",
  "Who's more likely to cry during a movie?",
  "Who's more likely to forget an anniversary?",
  "Who's more likely to start a dance party in the kitchen?",
  "Who's more likely to apologize first after a fight?",
  "Who's more likely to order dessert for the table?",
  "Who's more likely to get lost even with GPS?",
  "Who's more likely to send a good morning text?",
  "Who's more likely to hog the blankets at night?",
  "Who's more likely to suggest a spontaneous road trip?",
  "Who's more likely to remember everyone's birthday?",
  "Who's more likely to burn something while cooking?",
  "Who's more likely to fall asleep during a movie?",
  "Who's more likely to take forever getting ready?",
  "Who's more likely to start singing in public?",
  "Who's more likely to win an argument?",
  "Who's more likely to be the bigger flirt?",
  "Who's more likely to plan the vacation?",
  "Who's more likely to spend money on something silly?",
  "Who's more likely to get hangry?",
  "Who's more likely to befriend a stranger?",
  "Who's more likely to send a meme at 2 AM?",
  "Who's more likely to cry at a wedding?",
  "Who's more likely to be the designated photographer?",
  "Who's more likely to suggest staying in over going out?",
  "Who's more likely to have a secret snack stash?",
  "Who's more likely to be the first one on the dance floor?",
  "Who's more likely to forget where they parked?",
  "Who's more likely to say \"I love you\" first?",
  "Who's more likely to pick the restaurant?",
  "Who's more likely to binge a new show in one weekend?",
  "Who's more likely to be the cuddlier one?",
  "Who's more likely to get competitive during a game?",
  "Who's more likely to leave voice notes instead of texting?",
  "Who's more likely to wake up early on a weekend?",
  "Who's more likely to be the messy one?",
  "Who's more likely to plan a picnic?",
  "Who's more likely to talk to pets like they're people?",
  "Who's more likely to suggest a couple selfie?",
  "Who's more likely to double-text when nervous?",
  "Who's more likely to cry happy tears?",
  "Who's more likely to forget to reply for hours?",
  "Who's more likely to plan every detail of a trip?",
  "Who's more likely to suggest trying a new restaurant?",
  "Who's more likely to fall for a scam email?",
  "Who's more likely to be the peacemaker in a group?",
  "Who's more likely to have a five-step skincare routine?",
  "Who's more likely to laugh at their own jokes?",
  "Who's more likely to read the menu before arriving?",
  "Who's more likely to suggest a couples workout?",
  "Who's more likely to keep every ticket stub and memento?",
  "Who's more likely to be the designated driver?",
  "Who's more likely to start a deep conversation at midnight?",
  "Who's more likely to overshare on social media?",
  "Who's more likely to be scared of spiders?",
  "Who's more likely to suggest a board game night?",
  "Who's more likely to remember what you ordered last time?",
  "Who's more likely to be the early bird?",
  "Who's more likely to suggest rewatching a comfort show?",
  "Who's more likely to buy gifts \"just because\"?",
  "Who's more likely to get sunburned on vacation?",
  "Who's more likely to initiate a hug after a long day?",
  "Who's more likely to be the better cook?",
  "Who's more likely to talk through a problem immediately?",
  "Who's more likely to need alone time to recharge?",
  "Who's more likely to suggest a fancy date night?",
  "Who's more likely to be the bigger foodie?",
  "Who's more likely to cry during a commercial?",
  "Who's more likely to be the planner for holidays?",
  "Who's more likely to suggest a staycation?",
  "Who's more likely to win at trivia night?",
  "Who's more likely to be the handyman or handywoman?",
  "Who's more likely to suggest matching outfits?",
  "Who's more likely to be the life of the party?",
  "Who's more likely to read relationship advice online?",
  "Who's more likely to suggest a digital detox day?",
  "Who's more likely to be the sentimental one?",
  "Who's more likely to suggest adopting a pet?",
  "Who's more likely to be the better gift wrapper?",
  "Who's more likely to start a pillow fight?",
  "Who's more likely to be the one who says \"we need to talk\"?",
  "Who's more likely to suggest a couples bucket list?",
  "Who's more likely to be the bigger procrastinator?",
  "Who's more likely to suggest learning a language together?",
  "Who's more likely to be the one who fixes things around the house?",
  "Who's more likely to suggest a sunrise hike?",
  "Who's more likely to be the bigger dreamer?",
  "Who's more likely to suggest writing love letters?",
  "Who's more likely to be the one who remembers inside jokes?",
  "Who's more likely to suggest a cooking class together?",
  "Who's more likely to be the more patient one?",
  "Who's more likely to suggest a thrift-store date?",
  "Who's more likely to be the one who initiates \"I'm sorry\"?",
  "Who's more likely to suggest stargazing?",
  "Who's more likely to be the bigger worrier?",
  "Who's more likely to suggest a no-phones dinner?",
  "Who's more likely to be the one who plans surprises for friends too?",
  "Who's more likely to suggest a couples journal?",
  "Who's more likely to be the better dancer?",
  "Who's more likely to suggest volunteering together?",
  "Who's more likely to be the one who needs the most reassurance?",
  "Who's more likely to suggest a random act of kindness for a stranger?",
  "Who's more likely to be the bigger romantic?",
  "Who's more likely to suggest building something together (furniture, garden, etc.)?",
  "Who's more likely to be the one who remembers anniversaries of small moments?",
  "Who's more likely to plan a surprise?",
  "Who's more likely to plan a surprise during a horror movie?",
  "Who's more likely to forget a password?",
  "Who's more likely to forget a password when meeting new friends?",
  "Who's more likely to cry during a commercial on a first date redo?",
  "Who's more likely to order too much food?",
  "Who's more likely to order too much food when packing for a trip?",
  "Who's more likely to start a group chat?",
  "Who's more likely to start a group chat at a wedding?",
  "Who's more likely to be late to everything?",
  "Who's more likely to be late to everything during game night?",
  "Who's more likely to remember a random detail?",
  "Who's more likely to remember a random detail when the Wi-Fi goes out?",
  "Who's more likely to binge a show in one day?",
  "Who's more likely to binge a show in one day on a rainy day?",
  "Who's more likely to suggest a spontaneous trip?",
  "Who's more likely to suggest a spontaneous trip when someone is sad?",
  "Who's more likely to take the perfect photo?",
  "Who's more likely to take the perfect photo during a grocery run?",
  "Who's more likely to win at board games?",
  "Who's more likely to win at board games at a concert?",
  "Who's more likely to lose their keys?",
  "Who's more likely to lose their keys when lost with GPS?",
  "Who's more likely to talk to strangers?",
  "Who's more likely to talk to strangers on a lazy Sunday?",
  "Who's more likely to oversleep on a weekend?",
  "Who's more likely to oversleep on a weekend when trying something new?",
  "Who's more likely to send a voice note?",
  "Who's more likely to send a voice note during an argument?",
  "Who's more likely to double-text when anxious?",
  "Who's more likely to double-text when anxious on vacation?",
  "Who's more likely to apologize first?",
  "Who's more likely to apologize first at a party?",
  "Who's more likely to hold a grudge longer?",
  "Who's more likely to hold a grudge longer when hangry?",
  "Who's more likely to plan every holiday?",
  "Who's more likely to plan every holiday after a long day?",
  "Who's more likely to wing a recipe?",
  "Who's more likely to wing a recipe on a road trip?",
  "Who's more likely to burn toast?",
  "Who's more likely to burn toast during a horror movie?",
  "Who's more likely to pick the restaurant when meeting new friends?",
  "Who's more likely to suggest staying in?",
  "Who's more likely to suggest staying in on a first date redo?",
  "Who's more likely to dance in public?",
  "Who's more likely to dance in public when packing for a trip?",
  "Who's more likely to sing in the shower?",
  "Who's more likely to sing in the shower at a wedding?",
  "Who's more likely to hog the blankets?",
  "Who's more likely to hog the blankets during game night?",
  "Who's more likely to steal fries off your plate?",
  "Who's more likely to steal fries off your plate when the Wi-Fi goes out?",
  "Who's more likely to read reviews for 30 minutes?",
  "Who's more likely to read reviews for 30 minutes on a rainy day?",
  "Who's more likely to impulse-buy something silly?",
  "Who's more likely to impulse-buy something silly when someone is sad?",
  "Who's more likely to keep every ticket stub?",
  "Who's more likely to keep every ticket stub during a grocery run?",
  "Who's more likely to fix something around the house?",
  "Who's more likely to fix something around the house at a concert?",
  "Who's more likely to call their mom first?",
  "Who's more likely to call their mom first when lost with GPS?",
  "Who's more likely to cry at a wedding on a lazy Sunday?",
  "Who's more likely to laugh at the wrong moment?",
  "Who's more likely to laugh at the wrong moment when trying something new?",
  "Who's more likely to start a deep talk at midnight?",
  "Who's more likely to start a deep talk at midnight during an argument?",
  "Who's more likely to forget an inside joke?",
  "Who's more likely to forget an inside joke on vacation?",
  "Who's more likely to remember anniversaries?",
  "Who's more likely to remember anniversaries at a party?",
  "Who's more likely to suggest couple selfies?",
  "Who's more likely to suggest couple selfies when hangry?",
  "Who's more likely to be the bigger flirt after a long day?",
  "Who's more likely to get competitive?",
  "Who's more likely to get competitive on a road trip?",
  "Who's more likely to need reassurance?",
  "Who's more likely to need reassurance during a horror movie?",
  "Who's more likely to offer reassurance?",
  "Who's more likely to offer reassurance when meeting new friends?",
  "Who's more likely to plan a picnic on a first date redo?",
  "Who's more likely to suggest a workout?",
  "Who's more likely to suggest a workout when packing for a trip?",
  "Who's more likely to skip the workout?",
  "Who's more likely to skip the workout at a wedding?",
  "Who's more likely to read relationship advice?",
  "Who's more likely to read relationship advice during game night?",
  "Who's more likely to write a love note?",
  "Who's more likely to write a love note when the Wi-Fi goes out?",
  "Who's more likely to hide a sweet surprise?",
  "Who's more likely to hide a sweet surprise on a rainy day?",
  "Who's more likely to be the designated photographer when someone is sad?",
  "Who's more likely to fall asleep during a movie during a grocery run?",
  "Who's more likely to plan a surprise when trying something new?",
  "Who's more likely to forget a password during an argument?",
  "Who's more likely to cry during a commercial on vacation?",
  "Who's more likely to order too much food at a party?",
  "Who's more likely to start a group chat when hangry?",
  "Who's more likely to be late to everything after a long day?",
  "Who's more likely to remember a random detail on a road trip?",
  "Who's more likely to binge a show in one day during a horror movie?",
  "Who's more likely to suggest a spontaneous trip when meeting new friends?",
  "Who's more likely to take the perfect photo on a first date redo?",
  "Who's more likely to win at board games when packing for a trip?",
  "Who's more likely to lose their keys at a wedding?",
  "Who's more likely to talk to strangers during game night?",
  "Who's more likely to oversleep on a weekend when the Wi-Fi goes out?",
  "Who's more likely to send a voice note on a rainy day?",
  "Who's more likely to double-text when anxious when someone is sad?",
  "Who's more likely to apologize first during a grocery run?",
  "Who's more likely to hold a grudge longer at a concert?",
  "Who's more likely to plan every holiday when lost with GPS?",
  "Who's more likely to wing a recipe on a lazy Sunday?",
  "Who's more likely to burn toast when trying something new?",
  "Who's more likely to pick the restaurant during an argument?",
  "Who's more likely to suggest staying in on vacation?",
  "Who's more likely to dance in public at a party?",
  "Who's more likely to sing in the shower when hangry?",
  "Who's more likely to hog the blankets after a long day?",
  "Who's more likely to steal fries off your plate on a road trip?",
  "Who's more likely to read reviews for 30 minutes during a horror movie?",
  "Who's more likely to impulse-buy something silly when meeting new friends?",
  "Who's more likely to keep every ticket stub on a first date redo?",
  "Who's more likely to fix something around the house when packing for a trip?",
  "Who's more likely to call their mom first at a wedding?",
  "Who's more likely to cry at a wedding during game night?",
  "Who's more likely to laugh at the wrong moment when the Wi-Fi goes out?",
  "Who's more likely to start a deep talk at midnight on a rainy day?",
  "Who's more likely to forget an inside joke when someone is sad?",
  "Who's more likely to remember anniversaries during a grocery run?",
  "Who's more likely to suggest couple selfies at a concert?",
  "Who's more likely to be the bigger flirt when lost with GPS?",
  "Who's more likely to get competitive on a lazy Sunday?",
  "Who's more likely to need reassurance when trying something new?",
  "Who's more likely to offer reassurance during an argument?",
  "Who's more likely to plan a picnic on vacation?",
  "Who's more likely to suggest a workout at a party?",
  "Who's more likely to skip the workout when hangry?",
  "Who's more likely to read relationship advice after a long day?",
  "Who's more likely to write a love note on a road trip?",
  "Who's more likely to hide a sweet surprise during a horror movie?",
  "Who's more likely to be the designated photographer when meeting new friends?",
  "Who's more likely to fall asleep during a movie on a first date redo?",
  "Who's more likely to plan a surprise when packing for a trip?",
  "Who's more likely to forget a password at a wedding?",
  "Who's more likely to cry during a commercial during game night?",
  "Who's more likely to order too much food when the Wi-Fi goes out?",
  "Who's more likely to start a group chat on a rainy day?",
  "Who's more likely to be late to everything when someone is sad?",
  "Who's more likely to remember a random detail during a grocery run?",
  "Who's more likely to binge a show in one day at a concert?",
  "Who's more likely to suggest a spontaneous trip when lost with GPS?",
  "Who's more likely to take the perfect photo on a lazy Sunday?",
  "Who's more likely to win at board games when trying something new?",
  "Who's more likely to lose their keys during an argument?",
  "Who's more likely to talk to strangers on vacation?",
  "Who's more likely to oversleep on a weekend at a party?",
  "Who's more likely to send a voice note when hangry?",
  "Who's more likely to double-text when anxious after a long day?",
  "Who's more likely to apologize first on a road trip?",
  "Who's more likely to hold a grudge longer during a horror movie?",
  "Who's more likely to plan every holiday when meeting new friends?",
  "Who's more likely to wing a recipe on a first date redo?",
  "Who's more likely to burn toast when packing for a trip?",
  "Who's more likely to pick the restaurant at a wedding?",
  "Who's more likely to suggest staying in during game night?",
  "Who's more likely to dance in public when the Wi-Fi goes out?",
  "Who's more likely to sing in the shower on a rainy day?",
  "Who's more likely to hog the blankets when someone is sad?",
  "Who's more likely to steal fries off your plate during a grocery run?",
  "Who's more likely to read reviews for 30 minutes at a concert?",
  "Who's more likely to impulse-buy something silly when lost with GPS?",
  "Who's more likely to keep every ticket stub on a lazy Sunday?",
  "Who's more likely to fix something around the house when trying something new?",
  "Who's more likely to call their mom first during an argument?",
  "Who's more likely to cry at a wedding on vacation?",
  "Who's more likely to laugh at the wrong moment at a party?",
  "Who's more likely to start a deep talk at midnight when hangry?",
  "Who's more likely to forget an inside joke after a long day?",
  "Who's more likely to remember anniversaries on a road trip?",
  "Who's more likely to suggest couple selfies during a horror movie?",
  "Who's more likely to be the bigger flirt when meeting new friends?",
  "Who's more likely to get competitive on a first date redo?",
  "Who's more likely to need reassurance when packing for a trip?",
  "Who's more likely to offer reassurance at a wedding?",
  "Who's more likely to plan a picnic during game night?",
  "Who's more likely to suggest a workout when the Wi-Fi goes out?",
  "Who's more likely to skip the workout on a rainy day?",
  "Who's more likely to read relationship advice when someone is sad?",
  "Who's more likely to write a love note during a grocery run?",
  "Who's more likely to hide a sweet surprise at a concert?",
  "Who's more likely to be the designated photographer when lost with GPS?",
  "Who's more likely to fall asleep during a movie on a lazy Sunday?",
  "Who's more likely to plan a surprise date on vacation?",
  "Who's more likely to plan a surprise date when stressed?",
  "Who's more likely to plan a surprise date after a long day?",
  "Who's more likely to plan a surprise date on a road trip?",
  "Who's more likely to plan a surprise date at a party?",
  "Who's more likely to plan a surprise date during an argument?",
  "Who's more likely to plan a surprise date on a lazy Sunday?",
  "Who's more likely to plan a surprise date when hangry?",
  "Who's more likely to plan a surprise date when meeting new people?",
  "Who's more likely to plan a surprise date during a horror movie?",
  "Who's more likely to plan a surprise date at a wedding?",
  "Who's more likely to plan a surprise date when the Wi-Fi is down?",
  "Who's more likely to plan a surprise date on a rainy day?",
  "Who's more likely to plan a surprise date during game night?",
  "Who's more likely to plan a surprise date when trying something new?",
  "Who's more likely to plan a surprise date at a concert?",
  "Who's more likely to plan a surprise date when packing for a trip?",
  "Who's more likely to plan a surprise date during a grocery run?",
  "Who's more likely to plan a surprise date on a first date redo?",
  "Who's more likely to plan a surprise date when someone is sad?",
  "Who's more likely to plan a surprise date during the holidays?",
  "Who's more likely to plan a surprise date on a workday morning?",
  "Who's more likely to plan a surprise date before bed?",
  "Who's more likely to plan a surprise date when celebrating good news?",
  "Who's more likely to plan a surprise date during a long drive?",
  "Who's more likely to plan a surprise date at a restaurant?",
  "Who's more likely to plan a surprise date when planning a surprise?",
  "Who's more likely to plan a surprise date during a power outage?",
  "Who's more likely to plan a surprise date on a hike?",
  "Who's more likely to stay up late binge-watching on vacation?",
  "Who's more likely to stay up late binge-watching when stressed?",
  "Who's more likely to stay up late binge-watching after a long day?",
  "Who's more likely to stay up late binge-watching on a road trip?",
  "Who's more likely to stay up late binge-watching at a party?",
  "Who's more likely to stay up late binge-watching during an argument?",
  "Who's more likely to stay up late binge-watching on a lazy Sunday?",
  "Who's more likely to stay up late binge-watching when hangry?",
  "Who's more likely to stay up late binge-watching when meeting new people?",
  "Who's more likely to stay up late binge-watching during a horror movie?",
  "Who's more likely to stay up late binge-watching at a wedding?",
  "Who's more likely to stay up late binge-watching when the Wi-Fi is down?",
  "Who's more likely to stay up late binge-watching on a rainy day?",
  "Who's more likely to stay up late binge-watching during game night?",
  "Who's more likely to stay up late binge-watching when trying something new?",
  "Who's more likely to stay up late binge-watching at a concert?",
  "Who's more likely to stay up late binge-watching when packing for a trip?",
  "Who's more likely to stay up late binge-watching during a grocery run?",
  "Who's more likely to stay up late binge-watching on a first date redo?",
  "Who's more likely to stay up late binge-watching when someone is sad?",
  "Who's more likely to stay up late binge-watching during the holidays?",
  "Who's more likely to stay up late binge-watching on a workday morning?",
  "Who's more likely to stay up late binge-watching before bed?",
  "Who's more likely to stay up late binge-watching when celebrating good news?",
  "Who's more likely to stay up late binge-watching during a long drive?",
  "Who's more likely to stay up late binge-watching at a restaurant?",
  "Who's more likely to stay up late binge-watching when planning a surprise?",
  "Who's more likely to stay up late binge-watching during a power outage?",
  "Who's more likely to stay up late binge-watching on a hike?",
  "Who's more likely to cry during a movie on vacation?",
  "Who's more likely to cry during a movie when stressed?",
  "Who's more likely to cry during a movie after a long day?",
  "Who's more likely to cry during a movie on a road trip?",
  "Who's more likely to cry during a movie at a party?",
  "Who's more likely to cry during a movie during an argument?",
  "Who's more likely to cry during a movie on a lazy Sunday?",
  "Who's more likely to cry during a movie when hangry?",
  "Who's more likely to cry during a movie when meeting new people?",
  "Who's more likely to cry during a movie during a horror movie?",
  "Who's more likely to cry during a movie at a wedding?",
  "Who's more likely to cry during a movie when the Wi-Fi is down?",
  "Who's more likely to cry during a movie on a rainy day?",
  "Who's more likely to cry during a movie during game night?",
  "Who's more likely to cry during a movie when trying something new?",
  "Who's more likely to cry during a movie at a concert?",
  "Who's more likely to cry during a movie when packing for a trip?",
  "Who's more likely to cry during a movie during a grocery run?",
  "Who's more likely to cry during a movie on a first date redo?",
  "Who's more likely to cry during a movie when someone is sad?",
  "Who's more likely to cry during a movie during the holidays?",
  "Who's more likely to cry during a movie on a workday morning?",
  "Who's more likely to cry during a movie before bed?",
  "Who's more likely to cry during a movie when celebrating good news?",
  "Who's more likely to cry during a movie during a long drive?",
  "Who's more likely to cry during a movie at a restaurant?",
  "Who's more likely to cry during a movie when planning a surprise?",
  "Who's more likely to cry during a movie during a power outage?",
  "Who's more likely to cry during a movie on a hike?",
  "Who's more likely to forget an anniversary on vacation?",
  "Who's more likely to forget an anniversary when stressed?",
  "Who's more likely to forget an anniversary after a long day?",
  "Who's more likely to forget an anniversary on a road trip?",
  "Who's more likely to forget an anniversary at a party?",
  "Who's more likely to forget an anniversary during an argument?",
  "Who's more likely to forget an anniversary on a lazy Sunday?",
  "Who's more likely to forget an anniversary when hangry?",
  "Who's more likely to forget an anniversary when meeting new people?",
  "Who's more likely to forget an anniversary during a horror movie?",
  "Who's more likely to forget an anniversary at a wedding?",
  "Who's more likely to forget an anniversary when the Wi-Fi is down?",
  "Who's more likely to forget an anniversary on a rainy day?",
  "Who's more likely to forget an anniversary during game night?",
  "Who's more likely to forget an anniversary when trying something new?",
  "Who's more likely to forget an anniversary at a concert?",
  "Who's more likely to forget an anniversary when packing for a trip?",
  "Who's more likely to forget an anniversary during a grocery run?",
  "Who's more likely to forget an anniversary on a first date redo?",
  "Who's more likely to forget an anniversary when someone is sad?",
  "Who's more likely to forget an anniversary during the holidays?",
  "Who's more likely to forget an anniversary on a workday morning?",
  "Who's more likely to forget an anniversary before bed?",
  "Who's more likely to forget an anniversary when celebrating good news?",
  "Who's more likely to forget an anniversary during a long drive?",
  "Who's more likely to forget an anniversary at a restaurant?",
  "Who's more likely to forget an anniversary when planning a surprise?",
  "Who's more likely to forget an anniversary during a power outage?",
  "Who's more likely to forget an anniversary on a hike?",
  "Who's more likely to start a dance party in the kitchen on vacation?",
  "Who's more likely to start a dance party in the kitchen when stressed?",
  "Who's more likely to start a dance party in the kitchen after a long day?",
  "Who's more likely to start a dance party in the kitchen on a road trip?",
  "Who's more likely to start a dance party in the kitchen at a party?",
  "Who's more likely to start a dance party in the kitchen during an argument?",
  "Who's more likely to start a dance party in the kitchen on a lazy Sunday?",
  "Who's more likely to start a dance party in the kitchen when hangry?",
  "Who's more likely to start a dance party in the kitchen when meeting new people?",
  "Who's more likely to start a dance party in the kitchen during a horror movie?",
  "Who's more likely to start a dance party in the kitchen at a wedding?",
  "Who's more likely to start a dance party in the kitchen when the Wi-Fi is down?",
  "Who's more likely to start a dance party in the kitchen on a rainy day?",
  "Who's more likely to start a dance party in the kitchen during game night?",
  "Who's more likely to start a dance party in the kitchen when trying something new?",
  "Who's more likely to start a dance party in the kitchen at a concert?",
  "Who's more likely to start a dance party in the kitchen when packing for a trip?",
  "Who's more likely to start a dance party in the kitchen during a grocery run?",
  "Who's more likely to start a dance party in the kitchen on a first date redo?",
  "Who's more likely to start a dance party in the kitchen when someone is sad?",
  "Who's more likely to start a dance party in the kitchen during the holidays?",
  "Who's more likely to start a dance party in the kitchen on a workday morning?",
  "Who's more likely to start a dance party in the kitchen before bed?",
  "Who's more likely to start a dance party in the kitchen when celebrating good news?",
  "Who's more likely to start a dance party in the kitchen during a long drive?",
  "Who's more likely to start a dance party in the kitchen at a restaurant?",
  "Who's more likely to start a dance party in the kitchen when planning a surprise?",
  "Who's more likely to start a dance party in the kitchen during a power outage?",
  "Who's more likely to start a dance party in the kitchen on a hike?",
  "Who's more likely to apologize first after a fight on vacation?",
  "Who's more likely to apologize first after a fight when stressed?",
  "Who's more likely to apologize first after a fight after a long day?",
  "Who's more likely to apologize first after a fight on a road trip?",
  "Who's more likely to apologize first after a fight at a party?",
  "Who's more likely to apologize first after a fight during an argument?",
  "Who's more likely to apologize first after a fight on a lazy Sunday?",
  "Who's more likely to apologize first after a fight when hangry?",
  "Who's more likely to apologize first after a fight when meeting new people?",
  "Who's more likely to apologize first after a fight during a horror movie?",
  "Who's more likely to apologize first after a fight at a wedding?",
  "Who's more likely to apologize first after a fight when the Wi-Fi is down?",
  "Who's more likely to apologize first after a fight on a rainy day?",
  "Who's more likely to apologize first after a fight during game night?",
  "Who's more likely to apologize first after a fight when trying something new?",
  "Who's more likely to apologize first after a fight at a concert?",
  "Who's more likely to apologize first after a fight when packing for a trip?",
  "Who's more likely to apologize first after a fight during a grocery run?",
  "Who's more likely to apologize first after a fight on a first date redo?",
  "Who's more likely to apologize first after a fight when someone is sad?",
  "Who's more likely to apologize first after a fight during the holidays?",
  "Who's more likely to apologize first after a fight on a workday morning?",
  "Who's more likely to apologize first after a fight before bed?",
  "Who's more likely to apologize first after a fight when celebrating good news?",
  "Who's more likely to apologize first after a fight during a long drive?",
  "Who's more likely to apologize first after a fight at a restaurant?",
  "Who's more likely to apologize first after a fight when planning a surprise?",
  "Who's more likely to apologize first after a fight during a power outage?",
  "Who's more likely to apologize first after a fight on a hike?",
  "Who's more likely to order dessert for the table on vacation?",
  "Who's more likely to order dessert for the table when stressed?",
  "Who's more likely to order dessert for the table after a long day?",
  "Who's more likely to order dessert for the table on a road trip?",
  "Who's more likely to order dessert for the table at a party?",
  "Who's more likely to order dessert for the table during an argument?",
  "Who's more likely to order dessert for the table on a lazy Sunday?",
  "Who's more likely to order dessert for the table when hangry?",
  "Who's more likely to order dessert for the table when meeting new people?",
  "Who's more likely to order dessert for the table during a horror movie?",
  "Who's more likely to order dessert for the table at a wedding?",
  "Who's more likely to order dessert for the table when the Wi-Fi is down?",
  "Who's more likely to order dessert for the table on a rainy day?",
  "Who's more likely to order dessert for the table during game night?",
  "Who's more likely to order dessert for the table when trying something new?",
  "Who's more likely to order dessert for the table at a concert?",
  "Who's more likely to order dessert for the table when packing for a trip?",
  "Who's more likely to order dessert for the table during a grocery run?",
  "Who's more likely to order dessert for the table on a first date redo?",
  "Who's more likely to order dessert for the table when someone is sad?",
  "Who's more likely to order dessert for the table during the holidays?",
  "Who's more likely to order dessert for the table on a workday morning?",
  "Who's more likely to order dessert for the table before bed?",
  "Who's more likely to order dessert for the table when celebrating good news?",
  "Who's more likely to order dessert for the table during a long drive?",
  "Who's more likely to order dessert for the table at a restaurant?",
  "Who's more likely to order dessert for the table when planning a surprise?",
  "Who's more likely to order dessert for the table during a power outage?",
  "Who's more likely to order dessert for the table on a hike?",
  "Who's more likely to get lost even with GPS on vacation?",
  "Who's more likely to get lost even with GPS when stressed?",
  "Who's more likely to get lost even with GPS after a long day?",
  "Who's more likely to get lost even with GPS on a road trip?",
  "Who's more likely to get lost even with GPS at a party?",
  "Who's more likely to get lost even with GPS during an argument?",
  "Who's more likely to get lost even with GPS on a lazy Sunday?",
  "Who's more likely to get lost even with GPS when hangry?",
  "Who's more likely to get lost even with GPS when meeting new people?",
  "Who's more likely to get lost even with GPS during a horror movie?",
  "Who's more likely to get lost even with GPS at a wedding?",
  "Who's more likely to get lost even with GPS when the Wi-Fi is down?",
  "Who's more likely to get lost even with GPS on a rainy day?",
  "Who's more likely to get lost even with GPS during game night?",
  "Who's more likely to get lost even with GPS when trying something new?",
  "Who's more likely to get lost even with GPS at a concert?",
  "Who's more likely to get lost even with GPS when packing for a trip?",
  "Who's more likely to get lost even with GPS during a grocery run?",
];
